Add ability to duplicate containers #39

diff --git a/distrobox-create b/distrobox-create
--- a/distrobox-create
+++ b/distrobox-create
@@ -7,7 +7,8 @@
 trap '[ "$?" -ne 0 ] && printf "\nAn error occurred\n"' EXIT
 
 # Defaults
-container_image="registry.fedoraproject.org/fedora-toolbox:35"
+container_duplicate=""
+container_image=""
 container_name="fedora-toolbox-35"
 container_user_gid="$(id -rg)"
 container_user_home="${HOME:-"/"}"
@@ -41,6 +42,7 @@ Options:
 
 	--image/-i:		image to use for the container	default: registry.fedoraproject.org/fedora-toolbox:35
 	--name/-n:		name for the distrobox		default: fedora-toolbox-35
+	--duplicate/-d:		container to use as base for a new container
 	--help/-h:		show this message
 	--verbose/-v:		show more verbosity
 	--version/-V:		show version
@@ -77,6 +79,13 @@ while :; do
 			shift
 		fi
 		;;
+	-d | --duplicate)
+		if [ -n "$2" ]; then
+			container_duplicate="$2"
+			shift
+			shift
+		fi
+		;;
 	--) # End of all options.
 		shift
 		break
@@ -91,6 +100,18 @@ set -o nounset
 # set verbosity
 if [ "${verbose}" -ne 0 ]; then
 	set -o xtrace
+fi
+
+# We cannot have both a duplicate AND an image name/
+if [ -n "${container_duplicate}" ] && [ -n "${container_image}" ]; then
+	printf >&2 "Error: Invalid arguments, choose only one between duplicate or image name.\n"
+	exit 2
+fi
+
+# If no duplicate option and no container image, let's choose a default
+# image to use. Fedora toolbox is a sensitive default
+if [ -z "${container_duplicate}" ] && [ -z "${container_image}" ]; then
+	container_image="registry.fedoraproject.org/fedora-toolbox:35"
 fi
 
 # We depend on a container manager let's be sure we have it
@@ -111,6 +132,52 @@ fi
 if [ "${verbose}" -ne 0 ]; then
 	container_manager="${container_manager} --log-level debug"
 fi
+
+duplicate_container() {
+	# We need to duplicate a container.
+	# to do this we will commit the container and create a new tag. Then use it
+	# as image for the new container.
+	#
+	# to perform this we first ensure the source container exists and that the
+	# source container is stopped, else the clone will not work,
+	container_source_status="$(${container_manager} inspect --type container \
+		"${container_duplicate}" --format '{{.State.Status}}')"
+	container_exists="$?"
+	# Does the container exists? check if inspect reported errors
+	if [ "${container_exists}" -gt 0 ]; then
+		# If not, prompt to create it first
+		printf >&2 "Cannot find container %s, does it exist?\n" "${container_duplicate}"
+		printf >&2 "\nTry running first:\n"
+		printf >&2 "\tdistrobox-create --name <name-of-container> --image <remote>/<docker>:<tag>\n"
+		return 1
+	fi
+	# If the container is not already running, we need to start if first
+	if [ "${container_source_status}" = "running" ]; then
+		printf >&2 "Container %s, is running.\nPlease stop it first.\n" "${container_duplicate}"
+		printf >&2 "Cannot duplicate a running container.\n"
+		return 1
+	fi
+
+	# Now we can extract the container ID and commit it to use as source image
+	# for the new container.
+	container_source_id="$(${container_manager} inspect --type container \
+		"${container_duplicate}" --format '{{.Id}}')"
+	container_commit_tag="${container_duplicate}:toolbox-$(date +%F)"
+
+	# Commit current container state to a new image tag
+	printf >&2 "Duplicating %s...\n" "${container_duplicate}"
+	if ! ${container_manager} container commit \
+		"${container_source_id}" "${container_commit_tag}" >/dev/null; then
+
+		printf >&2 "Cannot duplicate container: %s\n" "${container_duplicate}"
+		return 1
+	fi
+
+	# Return the image tag to use for the new container creation.
+	printf "%s" "${container_commit_tag}"
+	return 0
+
+}
 
 # Generate Podman or Docker command to execute.
 # Arguments:
@@ -224,6 +291,11 @@ if ${container_manager} inspect --type container "${container_name}" >/dev/null 
 	exit 0
 fi
 
+# if we are using the duplicate flag, let's set the image variable
+# to the output of container duplication
+if [ -n "${container_duplicate}" ]; then
+	container_image="$(duplicate_container)"
+fi
 # First, check if the image exists in the host.
 # If not prompt to download it.
 if ! ${container_manager} inspect --type image "${container_image}" >/dev/null 2>&1; then
