generate-entry: add new command to create and delete desktop entries for distroboxes
This utility is automatically called by create and rm, so newer
distroboxes created with this version onward will automatically be added
to you applications list.
This tool can also be called separately to create/recreate/remove an
entry.

Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

diff --git a/distrobox-generate-entry b/distrobox-generate-entry
--- a/distrobox-generate-entry
+++ b/distrobox-generate-entry
@@ -19,28 +19,12 @@
 # along with distrobox; if not, see <http://www.gnu.org/licenses/>.
 
 # POSIX
-# Optional env variables:
-#	DBX_CONTAINER_MANAGER
-#   DBX_CONTAINER_NAME
-#   DBX_NON_INTERACTIVE
-#	DBX_SUDO_PROGRAM
+trap '[ "$?" -ne 0 ] && printf "\nAn error occurred\n"' EXIT
 
-# Dont' run this command as sudo.
-if [ "$(id -u)" -eq 0 ]; then
-	printf >&2 "Running %s as sudo is not supported.\n" "$(basename "${0}")"
-	printf >&2 " try instead running:\n"
-	printf >&2 "	%s --root %s\n" "$(basename "${0}")" "$*"
-	exit 1
-fi
-
-# Defaults
 container_manager="autodetect"
 container_name="my-distrobox"
-force=0
-non_interactive=0
-rootful=0
+delete=0
 verbose=0
-distrobox_sudo_program="sudo"
 version="1.3.2"
 
 # Source configuration files, this is done in an hierarchy so local files have
@@ -59,14 +43,8 @@ for config_file in ${config_files}; do
 	# shellcheck disable=SC1090
 	[ -e "${config_file}" ] && . "${config_file}"
 done
-# Fixup non_interactive=[true|false], in case we find it in the config file(s)
-[ "${non_interactive}" = "true" ] && non_interactive=1
-[ "${non_interactive}" = "false" ] && non_interactive=0
-
 [ -n "${DBX_CONTAINER_MANAGER}" ] && container_manager="${DBX_CONTAINER_MANAGER}"
 [ -n "${DBX_CONTAINER_NAME}" ] && container_name="${DBX_CONTAINER_NAME}"
-[ -n "${DBX_NON_INTERACTIVE}" ] && non_interactive="${DBX_NON_INTERACTIVE}"
-[ -n "${DBX_SUDO_PROGRAM}" ] && distrobox_sudo_program="${DBX_SUDO_PROGRAM}"
 
 # Print usage to stdout.
 # Arguments:
@@ -79,21 +57,21 @@ distrobox version: ${version}
 
 Usage:
 
-	distrobox-rm --name container-name [--force]
-	distrobox-rm container-name [-f]
+	distrobox-generate-entry container-name [--delete]
 
 Options:
 
-	--name/-n:		name for the distrobox
-	--force/-f:		force deletion
-	--root/-r:		launch podman/docker with root privileges. Note that if you need root this is the preferred
-				way over "sudo distrobox" (note: if using a program other than 'sudo' for root privileges is necessary,
-				specify it through the DBX_SUDO_PROGRAM env variable, or 'distrobox_sudo_program' config variable)
 	--help/-h:		show this message
+	--delete/-d:		delete the entry
 	--verbose/-v:		show more verbosity
 	--version/-V:		show version
 EOF
 }
+
+if [ $# -eq 0 ]; then
+	show_help
+	exit
+fi
 
 # Parse arguments
 while :; do
@@ -103,10 +81,6 @@ while :; do
 			show_help
 			exit 0
 			;;
-		-r | --root)
-			shift
-			rootful=1
-			;;
 		-v | --verbose)
 			verbose=1
 			shift
@@ -115,19 +89,8 @@ while :; do
 			printf "distrobox: %s\n" "${version}"
 			exit 0
 			;;
-		-f | --force)
-			force=1
-			shift
-			;;
-		-n | --name)
-			if [ -n "$2" ]; then
-				container_name="$2"
-				shift
-				shift
-			fi
-			;;
-		-Y | --yes)
-			non_interactive=1
+		-d | --delete)
+			delete=1
 			shift
 			;;
 		--) # End of all options.
@@ -182,7 +145,7 @@ case "${container_manager}" in
 esac
 
 # Be sure we have a container manager to work with.
-if ! command -v "${container_manager}" > /dev/null; then
+if ! command -v "${container_manager}" > /dev/null && [ "${dryrun}" -eq 0 ]; then
 	# Error: we need at least one between docker or podman.
 	printf >&2 "Missing dependency: we need a container manager.\n"
 	printf >&2 "Please install one of podman or docker.\n"
@@ -192,69 +155,42 @@ if ! command -v "${container_manager}" > /dev/null; then
 	printf >&2 "\thttps://github.com/89luca89/distrobox/blob/main/docs/compatibility.md\n"
 	exit 127
 fi
+
 # add  verbose if -v is specified
 if [ "${verbose}" -ne 0 ]; then
 	container_manager="${container_manager} --log-level debug"
 fi
 
-# prepend sudo (or the specified sudo program) if we want podman or docker to be rootful
-if [ "${rootful}" -ne 0 ]; then
-	container_manager="${distrobox_sudo_program} ${container_manager}"
-fi
-
-# Inspect the container we're working with.
-container_status="$(${container_manager} inspect --type container \
-	"${container_name}" --format '{{.State.Status}}')"
-container_exists="$?"
-# Does the container exist? check if inspect reported errors
-if [ "${container_exists}" -gt 0 ]; then
-	# If not, prompt to create it first
-	printf >&2 "Cannot find container %s, does it exist?\n" "${container_name}"
+if [ -z "${container_name}" ]; then
+	printf >&2 "Please specify the name of the container.\n"
 	exit 1
 fi
 
-# If the container is not already running, we need to start if first
-if [ "${container_status}" = "running" ]; then
-	if [ "${force}" -ne 0 ]; then
-		printf >&2 "Stopping container %s\n" "${container_name}"
-		if ! ${container_manager} stop "${container_name}"; then
-			printf >&2 "Could not stop container %s\n" "${container_name}"
-			printf >&2 "Please stop container %s before deletion\n" "${container_name}"
-			printf >&2 "Run:\n\t%s stop %s" "${container_manager}" "${container_name}"
-			exit 1
-		fi
-	else
-		printf >&2 "Please stop container %s before deletion\n" "${container_name}"
-		printf >&2 "Run:\n\t%s stop %s\n" "${container_manager}" "${container_name}"
-		printf >&2 'or use the "--force" flag'
-		exit 1
-	fi
-fi
-if [ "${non_interactive}" -eq 0 ] && [ "${force}" -eq 0 ]; then
-	# Prompt to download it.
-	printf "Do you really want to delete %s? [Y/n]: " "${container_name}"
-	read -r response
-	response="${response:-"Y"}"
-else
-	response="yes"
+# If we delete, just ask confirmation and exit.
+if [ "${delete}" -ne 0 ]; then
+	rm "${HOME}/.local/share/applications/${container_name}.desktop"
+	exit $?
 fi
 
-# Accept only y,Y,Yes,yes,n,N,No,no.
-case "${response}" in
-	y | Y | Yes | yes | YES)
-		# Remove the container
-		${container_manager} rm "${container_name}"
+if ! ${container_manager} inspect --type container "${container_name}" >/dev/null; then
+	printf >&2 "Cannot find container %s. Please create it first.\n" "${container_name}"
+	exit 1
+fi
 
-		# We've deleted the box, let's also delete the entry
-		"$(dirname "${0}")/distrobox-generate-entry" "${container_name}" --delete
-		;;
-	n | N | No | no | NO)
-		printf "Aborted.\n"
-		exit 0
-		;;
-	*) # Default case: If no more options then break out of the loop.
-		printf >&2 "Invalid input.\n"
-		printf >&2 "The available choices are: y,Y,Yes,yes,YES or n,N,No,no,NO.\nExiting.\n"
-		exit 1
-		;;
-esac
+
+distrobox_path="$(dirname "$(realpath "${0}")")"
+entry_name="$(echo "${container_name}" | cut -c1 | tr "[:lower:]" "[:upper:]")$(echo "${container_name}" | cut -c2-)"
+
+TEMPLATE="[Desktop Entry]
+Name=${entry_name}
+GenericName=Terminal entering ${entry_name}
+Comment=Terminal entering ${entry_name}
+Keywords=distrobox;
+Exec=$distrobox_path/distrobox enter ${container_name}
+Icon=$HOME/.local/share/icons/terminal-distrobox-icon.png
+NoDisplay=false
+Terminal=true
+Type=Application
+Category=Distrobox;System;Utility"
+
+echo "$TEMPLATE" > "${HOME}/.local/share/applications/${container_name}.desktop"
