WIP: support environment variables to change defaults
Implement use of environment variables to change defaults like:

 - container manager
 - default image to use
 - default name to use
 - interactivity

Variables will be respectively:

- DBX_CONTAINER_MANAGER
- DBX_CONTAINER_IMAGE
- DBX_CONTAINER_NAME
- DBX_NON_INTERACTIVE

This work will open support for future configuration rc-style files,
which can be simply sourced.

For now this will ensure the possibility to alter the defaults using
environment files, lowering the need to use flags in normal use.

---

Simple use:

Add this to your ~/.profile

```sh
export DBX_CONTAINER_IMAGE="ubuntu:22.04"
export DBX_CONTAINER_MANAGER="docker"
export DBX_CONTAINER_NAME="test-env"
```

Now you can simply use:

- distrobox create
- distrobox enter
- distrobox rm
- distrobox stop

without having to specify your custom name or image, and all of them
will be automatically executed with docker, even if podman is present.

This work is an initial implementation for #193

diff --git a/distrobox-create b/distrobox-create
--- a/distrobox-create
+++ b/distrobox-create
@@ -23,6 +23,7 @@
 #	HOME
 #	USER
 # Optional env variables:
+#	DBX_CONTAINER_MANAGER
 #	DBX_CONTAINER_IMAGE
 #	DBX_CONTAINER_NAME
 #	DBX_NON_INTERACTIVE
@@ -44,6 +45,7 @@ container_clone=""
 container_image="${DBX_CONTAINER_IMAGE:-""}"
 container_image_default="registry.fedoraproject.org/fedora-toolbox:35"
 container_init_hook=""
+container_manager="${DBX_CONTAINER_MANAGER:-"autodetect"}"
 container_manager_additional_flags=""
 container_name="${DBX_CONTAINER_NAME:-""}"
 container_user_custom_home=""
@@ -242,22 +244,40 @@ fi
 
 # We depend on a container manager let's be sure we have it
 # First we use podman, else docker
-container_manager="podman"
+case "${container_manager}" in
+autodetect)
+	if command -v podman >/dev/null; then
+		container_manager="podman"
+	elif command -v docker >/dev/null; then
+		container_manager="docker"
+	else
+		container_manager="not_found"
+	fi
+	;;
+podman)
+	container_manager="podman"
+	;;
+docker)
+	container_manager="docker"
+	;;
+*)
+	printf >&2 "Invalid input %s.\n" "${container_manager}"
+	printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
+	container_manager="not_found"
+	;;
+esac
+
 # Be sure we have a container manager to work with.
 if ! command -v "${container_manager}" >/dev/null; then
-	# If no podman, try docker.
-	container_manager="docker"
-	if ! command -v docker >/dev/null; then
-		# Error: we need at least one between docker or podman.
-		printf >&2 "Missing dependency: we need a container manager.\n"
-		printf >&2 "Please install one of podman or docker.\n"
-		printf >&2 "You can follow the documentation on:\n"
-		printf >&2 "\tman distrobox-compatibility\n"
-		printf >&2 "or:\n"
-		printf >&2 "\thttps://github.com/89luca89/distrobox/blob/main/docs/compatibility.md\n"
-		if [ "${dryrun}" -eq 0 ]; then
-			exit 127
-		fi
+	# Error: we need at least one between docker or podman.
+	printf >&2 "Missing dependency: we need a container manager.\n"
+	printf >&2 "Please install one of podman or docker.\n"
+	printf >&2 "You can follow the documentation on:\n"
+	printf >&2 "\tman distrobox-compatibility\n"
+	printf >&2 "or:\n"
+	printf >&2 "\thttps://github.com/89luca89/distrobox/blob/main/docs/compatibility.md\n"
+	if [ "${dryrun}" -eq 0 ]; then
+		exit 127
 	fi
 fi
 # add  verbose if -v is specified
diff --git a/distrobox-rm b/distrobox-rm
--- a/distrobox-rm
+++ b/distrobox-rm
@@ -19,6 +19,10 @@
 # along with distrobox; if not, see <http://www.gnu.org/licenses/>.
 
 # POSIX
+# Optional env variables:
+#   DBX_CONTAINER_NAME
+#   DBX_NON_INTERACTIVE
+#	DBX_CONTAINER_MANAGER
 
 # Dont' run this command as sudo.
 if [ "$(id -u)" -eq 0 ]; then
@@ -31,9 +35,10 @@ if [ "$(id -u)" -eq 0 ]; then
 fi
 
 # Defaults
-container_name="${DB_CONTAINER_NAME:-""}"
-force=0
+container_manager="${DBX_CONTAINER_MANAGER:-"autodetect"}"
+container_name="${DBX_CONTAINER_NAME:-""fedora-toolbox-35}"
 non_interactive="${DBX_NON_INTERACTIVE:-0}"
+force=0
 verbose=0
 version="1.2.14"
 
@@ -121,21 +126,39 @@ fi
 
 # We depend on a container manager let's be sure we have it
 # First we use podman, else docker
-container_manager="podman"
-# Be sure we have a container manager to work with.
-if ! command -v podman >/dev/null; then
-	# If no podman, try docker.
-	container_manager="docker"
-	if ! command -v docker >/dev/null; then
-		# Error: we need at least one between docker or podman.
-		printf >&2 "Missing dependency: we need a container manager.\n"
-		printf >&2 "Please install one of podman or docker.\n"
-		printf >&2 "You can follow the documentation on:\n"
-		printf >&2 "\tman distrobox-compatibility\n"
-		printf >&2 "or:\n"
-		printf >&2 "\thttps://github.com/89luca89/distrobox/blob/main/docs/compatibility.md\n"
-		exit 127
+case "${container_manager}" in
+autodetect)
+	if command -v podman >/dev/null; then
+		container_manager="podman"
+	elif command -v docker >/dev/null; then
+		container_manager="docker"
+	else
+		container_manager="not_found"
 	fi
+	;;
+podman)
+	container_manager="podman"
+	;;
+docker)
+	container_manager="docker"
+	;;
+*)
+	printf >&2 "Invalid input %s.\n" "${container_manager}"
+	printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
+	container_manager="not_found"
+	;;
+esac
+
+# Be sure we have a container manager to work with.
+if ! command -v "${container_manager}" >/dev/null; then
+	# Error: we need at least one between docker or podman.
+	printf >&2 "Missing dependency: we need a container manager.\n"
+	printf >&2 "Please install one of podman or docker.\n"
+	printf >&2 "You can follow the documentation on:\n"
+	printf >&2 "\tman distrobox-compatibility\n"
+	printf >&2 "or:\n"
+	printf >&2 "\thttps://github.com/89luca89/distrobox/blob/main/docs/compatibility.md\n"
+	exit 127
 fi
 # add  verbose if -v is specified
 if [ "${verbose}" -ne 0 ]; then
