formatting
Signed-off-by: Mišo Barišić <me@misobarisic.com>

diff --git a/distrobox-list b/distrobox-list
--- a/distrobox-list
+++ b/distrobox-list
@@ -85,38 +85,38 @@ EOF
 # Parse arguments
 while :; do
 	case $1 in
-	-h | --help)
-		# Call a "show_help" function to display a synopsis, then exit.
-		show_help
-		exit 0
-		;;
-	--no-color)
-		shift
-		no_color=1
-		;;
-	-r | --root)
-		shift
-		rootful=1
-		;;
-	-v | --verbose)
-		verbose=1
-		shift
-		;;
-	-V | --version)
-		printf "distrobox: %s\n" "${version}"
-		exit 0
-		;;
-	--) # End of all options.
-		shift
-		break
-		;;
-	-*) # Invalid options.
-		printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
-		show_help
-		exit 1
-		;;
-	*) # Default case: If no more options then break out of the loop.
-		break ;;
+		-h | --help)
+			# Call a "show_help" function to display a synopsis, then exit.
+			show_help
+			exit 0
+			;;
+		--no-color)
+			shift
+			no_color=1
+			;;
+		-r | --root)
+			shift
+			rootful=1
+			;;
+		-v | --verbose)
+			verbose=1
+			shift
+			;;
+		-V | --version)
+			printf "distrobox: %s\n" "${version}"
+			exit 0
+			;;
+		--) # End of all options.
+			shift
+			break
+			;;
+		-*) # Invalid options.
+			printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
+			show_help
+			exit 1
+			;;
+		*) # Default case: If no more options then break out of the loop.
+			break ;;
 	esac
 done
 
@@ -130,23 +130,23 @@ fi
 # We depend on a container manager let's be sure we have it
 # First we use podman, else docker
 case "${container_manager}" in
-autodetect)
-	if command -v podman > /dev/null; then
+	autodetect)
+		if command -v podman > /dev/null; then
+			container_manager="podman"
+		elif command -v docker > /dev/null; then
+			container_manager="docker"
+		fi
+		;;
+	podman)
 		container_manager="podman"
-	elif command -v docker > /dev/null; then
+		;;
+	docker)
 		container_manager="docker"
-	fi
-	;;
-podman)
-	container_manager="podman"
-	;;
-docker)
-	container_manager="docker"
-	;;
-*)
-	printf >&2 "Invalid input %s.\n" "${container_manager}"
-	printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
-	;;
+		;;
+	*)
+		printf >&2 "Invalid input %s.\n" "${container_manager}"
+		printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
+		;;
 esac
 
 # Be sure we have a container manager to work with.
