init: add upgrade mode
Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

diff --git a/distrobox-init b/distrobox-init
--- a/distrobox-init
+++ b/distrobox-init
@@ -29,6 +29,7 @@ trap '[ "$?" -ne 0 ] && printf "Error: An error occurred\n"' EXIT
 # Defaults
 init=0
 init_hook=""
+upgrade=0
 pre_init_hook=""
 verbose=0
 version="1.3.2"
@@ -54,6 +55,7 @@ Options:
 	--help/-h:		show this message
 	--init/-I:		whether to use or not init
 	--pre-init-hooks:	commands to execute prior to init
+	--upgrade/-U:		run init in upgrade mode
 	--verbose/-v:		show more verbosity
 	--version/-V:		show version
 	--:			end arguments execute the rest as command to execute during init
@@ -75,6 +77,10 @@ while :; do
 		-V | --version)
 			printf "distrobox: %s\n" "${version}"
 			exit 0
+			;;
+		-U | --upgrade)
+			shift
+			upgrade=1
 			;;
 		-n | --name)
 			if [ -n "$2" ]; then
@@ -133,13 +139,6 @@ while :; do
 	esac
 done
 
-set -o errexit
-set -o nounset
-# set verbosity
-if [ "${verbose}" -ne 0 ]; then
-	set -o xtrace
-fi
-
 # Check we're running inside a container and not on the host
 if [ ! -f /run/.containerenv ] && [ ! -f /.dockerenv ]; then
 	printf >&2 "You must run %s inside a container!\n" " $(basename "$0")"
@@ -151,10 +150,18 @@ fi
 
 # Ensure the foundamental variables are set and not empty, we will not proceed if
 # they are not all set.
-[ -z "${container_user_gid}" ] && printf "Error: Invalid arguments, missing user gud\n" && exit 2
-[ -z "${container_user_home}" ] && printf "Error: Invalid argument, missing user home\n" && exit 2
-[ -z "${container_user_name}" ] && printf "Error: Invalid arguments, missing username\n" && exit 2
-[ -z "${container_user_uid}" ] && printf "Error: Invalid arguments, missing user uid\n" && exit 2
+if [ "${upgrade}" -eq 0 ]; then
+	[ -z "${container_user_gid}" ] && printf "Error: Invalid arguments, missing user gud\n" && exit 2
+	[ -z "${container_user_home}" ] && printf "Error: Invalid argument, missing user home\n" && exit 2
+	[ -z "${container_user_name}" ] && printf "Error: Invalid arguments, missing username\n" && exit 2
+	[ -z "${container_user_uid}" ] && printf "Error: Invalid arguments, missing user uid\n" && exit 2
+fi
+set -o errexit
+set -o nounset
+# set verbosity
+if [ "${verbose}" -ne 0 ]; then
+	set -o xtrace
+fi
 
 # Bind mount or error.
 # Arguments:
@@ -223,7 +230,7 @@ if [ "${shell_pkg}" = "ash" ]; then
 fi
 
 # Check if dependencies are met for the script to run.
-if ! command -v find || ! command -v mount || ! command -v passwd ||
+if [ "${upgrade}" -ne 0 ] || ! command -v find || ! command -v mount || ! command -v passwd ||
 	! command -v sudo || ! command -v useradd || ! command -v diff ||
 	! command -v pinentry || ! command -v wget || ! command -v curl ||
 	! command -v less || ! command -v bc ||
@@ -235,6 +242,11 @@ if ! command -v find || ! command -v mount || ! command -v passwd ||
 	#	sudo, mount, find
 	#	passwd, groupadd and useradd
 	if command -v apk; then
+		# If we need to upgrade, do it and exit, no further action required.
+		if [ "${upgrade}" -ne 0 ]; then
+			apk upgrade
+			exit
+		fi
 		# Check if shell_pkg is available in distro's repo. If not we
 		# fall back to bash, and we set the SHELL variable to bash so
 		# that it is set up correctly for the user.
@@ -259,6 +271,12 @@ if ! command -v find || ! command -v mount || ! command -v passwd ||
 			vte3
 
 	elif command -v apt-get; then
+		# If we need to upgrade, do it and exit, no further action required.
+		if [ "${upgrade}" -ne 0 ]; then
+			apt update
+			apt upgrade -y
+			exit
+		fi
 		# In Ubuntu official images, dpkg is configured to ignore locale and docs
 		# This however, results in a rather poor out-of-the-box experience
 		# So, let's enable them.
@@ -293,6 +311,11 @@ if ! command -v find || ! command -v mount || ! command -v passwd ||
 			util-linux
 
 	elif command -v dnf; then
+		# If we need to upgrade, do it and exit, no further action required.
+		if [ "${upgrade}" -ne 0 ]; then
+			dnf upgrade -y
+			exit
+		fi
 		# In dnf family official images, dnf is configured to ignore locale and docs
 		# This however, results in a rather poor out-of-the-box experience
 		# So, let's enable them.
@@ -347,6 +370,11 @@ if ! command -v find || ! command -v mount || ! command -v passwd ||
 			vte
 
 	elif command -v microdnf; then
+		# If we need to upgrade, do it and exit, no further action required.
+		if [ "${upgrade}" -ne 0 ]; then
+			microdnf upgrade -y
+			exit
+		fi
 		# Check if shell_pkg is available in distro's repo. If not we
 		# fall back to bash, and we set the SHELL variable to bash so
 		# that it is set up correctly for the user.
@@ -371,6 +399,11 @@ if ! command -v find || ! command -v mount || ! command -v passwd ||
 		# vte-profile
 
 	elif command -v pacman; then
+		# If we need to upgrade, do it and exit, no further action required.
+		if [ "${upgrade}" -ne 0 ]; then
+			pacman -Syyu --noconfirm
+			exit
+		fi
 		# In archlinux  official images, pacman is configured to ignore locale and docs
 		# This however, results in a rather poor out-of-the-box experience
 		# So, let's enable them.
@@ -401,6 +434,11 @@ if ! command -v find || ! command -v mount || ! command -v passwd ||
 			vte-common
 
 	elif command -v slackpkg; then
+		# If we need to upgrade, do it and exit, no further action required.
+		if [ "${upgrade}" -ne 0 ]; then
+			yes | slackpkg upgrade-all -default_answer=yes -batch=yes
+			exit
+		fi
 		slackpkg update
 		# Check if shell_pkg is available in distro's repo. If not we
 		# fall back to bash, and we set the SHELL variable to bash so
@@ -426,6 +464,11 @@ if ! command -v find || ! command -v mount || ! command -v passwd ||
 			util-linux
 
 	elif command -v swupd; then
+		# If we need to upgrade, do it and exit, no further action required.
+		if [ "${upgrade}" -ne 0 ]; then
+			swupd update
+			exit
+		fi
 		# Here we do not handle shell_pkg as shells are already all bundled
 		# together in "shells"
 		swupd bundle-add \
@@ -438,6 +481,11 @@ if ! command -v find || ! command -v mount || ! command -v passwd ||
 			wget
 
 	elif command -v xbps-install; then
+		# If we need to upgrade, do it and exit, no further action required.
+		if [ "${upgrade}" -ne 0 ]; then
+			xbps-install -Syu
+			exit
+		fi
 		# Ensure we avoid errors by keeping xbps updated
 		xbps-install -Syu xbps
 		# Check if shell_pkg is available in distro's repo. If not we
@@ -462,6 +510,11 @@ if ! command -v find || ! command -v mount || ! command -v passwd ||
 			util-linux
 
 	elif command -v yum; then
+		# If we need to upgrade, do it and exit, no further action required.
+		if [ "${upgrade}" -ne 0 ]; then
+			yum upgrade -y
+			exit
+		fi
 		# In yum family official images, yum is configured to ignore locale and docs
 		# This however, results in a rather poor out-of-the-box experience
 		# So, let's enable them.
@@ -492,6 +545,11 @@ if ! command -v find || ! command -v mount || ! command -v passwd ||
 			vte-profile
 
 	elif command -v zypper; then
+		# If we need to upgrade, do it and exit, no further action required.
+		if [ "${upgrade}" -ne 0 ]; then
+			zypper dup -y
+			exit
+		fi
 		if ! zypper install -y "${shell_pkg}"; then
 			SHELL="/bin/bash"
 			shell_pkg="bash"
