Feature/move socket mounts (#75)
* init: ensure find command is installed
* create/init: move host's socket discovery and mount from create to init. Also now use symlinks #73

diff --git a/distrobox-init b/distrobox-init
--- a/distrobox-init
+++ b/distrobox-init
@@ -194,6 +194,7 @@ if ! command -v mount || ! command -v passwd ||
 	if command -v apk; then
 		apk add \
 			"${shell_pkg}" \
+			findutils \
 			ncurses \
 			procps \
 			shadow \
@@ -205,6 +206,7 @@ if ! command -v mount || ! command -v passwd ||
 		apt-get update
 		apt-get install -y \
 			"${shell_pkg}" \
+			findutils \
 			ncurses-base \
 			passwd \
 			procps \
@@ -214,6 +216,7 @@ if ! command -v mount || ! command -v passwd ||
 	elif command -v dnf; then
 		dnf install -y \
 			"${shell_pkg}" \
+			findutils \
 			ncurses-base \
 			passwd \
 			procps-ng \
@@ -224,6 +227,7 @@ if ! command -v mount || ! command -v passwd ||
 	elif command -v pacman; then
 		pacman -Sy --noconfirm \
 			"${shell_pkg}" \
+			findutils \
 			ncurses \
 			procps-ng \
 			shadow \
@@ -234,6 +238,7 @@ if ! command -v mount || ! command -v passwd ||
 		slackpkg update
 		yes | slackpkg install -default_answer=yes -batch=yes \
 			"${shell_pkg}" \
+			findutils \
 			ncurses \
 			procps \
 			shadow \
@@ -243,6 +248,7 @@ if ! command -v mount || ! command -v passwd ||
 	elif command -v xbps-install; then
 		xbps-install -Sy \
 			"${shell_pkg}" \
+			findutils \
 			ncurses-base \
 			procps-ng \
 			shadow \
@@ -252,6 +258,7 @@ if ! command -v mount || ! command -v passwd ||
 	elif command -v yum; then
 		yum install -y \
 			"${shell_pkg}" \
+			findutils \
 			ncurses-base \
 			passwd \
 			procps \
@@ -262,6 +269,7 @@ if ! command -v mount || ! command -v passwd ||
 	elif command -v zypper; then
 		zypper install -y \
 			"${shell_pkg}" \
+			findutils \
 			ncurses \
 			procps \
 			shadow \
@@ -299,6 +307,24 @@ HOST_MOUNTS="
 for host_mount in ${HOST_MOUNTS}; do
 	if ! mount_bind /run/host"${host_mount}" "${host_mount}" rw; then
 		printf "Warning: Cannot bind mound %s to /run/host%s\n" "${host_mount}" "${host_mount}"
+	fi
+done
+
+# Find all the user's socket and mount them inside the container
+# this will allow for continuity of functionality between host and container
+#
+# for example using `podman --remote` to control the host's podman from inside
+# the container or accessing docker and libvirt sockets.
+host_sockets="$(find /run/host/run -name 'user' -prune -o -type s -print 2>/dev/null || :)"
+for host_socket in ${host_sockets}; do
+	container_socket="$(echo "${host_socket}" | sed 's|/run/host||g')"
+	# Check if the socket already exists or the symlink already esists
+	if [ ! -S "${container_socket}" ] && [ ! -L "${container_socket}" ]; then
+		# link it.
+		mkdir -p "$(dirname "${container_socket}")"
+		if ! ln -s "${host_socket}" "${container_socket}"; then
+			printf "Warning: Cannot link socket %s to %s\n" "${host_socket}" "${container_socket}"
+		fi
 	fi
 done
 
