enter: improve logging output in case of error in init

diff --git a/distrobox-init b/distrobox-init
--- a/distrobox-init
+++ b/distrobox-init
@@ -5,7 +5,7 @@
 #	USER
 #	SHELL
 
-trap '[ "$?" -ne 0 ] && printf "An error occurred\n"' EXIT
+trap '[ "$?" -ne 0 ] && printf "Error: An error occurred\n"' EXIT
 
 # Defaults
 verbose=0
@@ -204,7 +204,8 @@ if ! command -v mount || ! command -v passwd ||
 	elif command -v zypper; then
 		zypper install -y --no-recommends sudo shadow procps util-linux "${shell_pkg}"
 	else
-		printf >&2 "FAILED TO INSTALL BASE DEPENDENCIES\n"
+		printf >&2 "Error: could not find a supported package manager.\n"
+		printf >&2 "Error: could not set up base dependencies.\n"
 		# Exit as command not found
 		exit 127
 	fi
