init: add other useful bind mounts, selinux, systemd-resolve

diff --git a/distrobox-init b/distrobox-init
--- a/distrobox-init
+++ b/distrobox-init
@@ -227,12 +227,18 @@ done
 
 # We'll also bind mount READ-WRITE useful mountpoints to pass external drives and libvirt from
 # the host to the container
-HOST_MOUNTS="/media /run/media /mnt /run/systemd/journal /run/libvirt /var/mnt /var/lib/libvirt"
+HOST_MOUNTS="/media /run/media /mnt /var/mnt /run/systemd/journal /run/systemd/resolve /run/libvirt /var/lib/libvirt"
 for host_mount in ${HOST_MOUNTS}; do
 	if ! mount_bind /run/host"${host_mount}" "${host_mount}" rw; then
 		printf "Warning: Cannot bind mound %s to /run/host%s\n" "${host_mount}" "${host_mount}"
 	fi
 done
+
+if [ -d /sys/fs/selinux ] 2>&3; then
+    if ! mount_bind /usr/share/empty /sys/fs/selinux; then
+		printf "Warning: Cannot bind mound /usr/share/empty to /sys/fs/selinux"
+    fi
+fi
 
 # Do not check fqdn when doing sudo, it will not work anyways
 if ! grep -q 'Defaults !fqdn' /etc/sudoers; then
