format
Signed-off-by: Mišo Barišić <me@misobarisic.com>

diff --git a/distrobox-list b/distrobox-list
--- a/distrobox-list
+++ b/distrobox-list
@@ -63,7 +63,7 @@ done
 # Outputs:
 #   print usage with examples.
 show_help() {
-	cat << EOF
+	cat <<EOF
 distrobox version: ${version}
 
 Usage:
@@ -85,38 +85,38 @@ EOF
 # Parse arguments
 while :; do
 	case $1 in
-		-h | --help)
-			# Call a "show_help" function to display a synopsis, then exit.
-			show_help
-			exit 0
-			;;
-		--no-color)
-			shift
-			no_color=1
-			;;
-		-r | --root)
-			shift
-			rootful=1
-			;;
-		-v | --verbose)
-			verbose=1
-			shift
-			;;
-		-V | --version)
-			printf "distrobox: %s\n" "${version}"
-			exit 0
-			;;
-		--) # End of all options.
-			shift
-			break
-			;;
-		-*) # Invalid options.
-			printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
-			show_help
-			exit 1
-			;;
-		*) # Default case: If no more options then break out of the loop.
-			break ;;
+	-h | --help)
+		# Call a "show_help" function to display a synopsis, then exit.
+		show_help
+		exit 0
+		;;
+	--no-color)
+		shift
+		no_color=1
+		;;
+	-r | --root)
+		shift
+		rootful=1
+		;;
+	-v | --verbose)
+		verbose=1
+		shift
+		;;
+	-V | --version)
+		printf "distrobox: %s\n" "${version}"
+		exit 0
+		;;
+	--) # End of all options.
+		shift
+		break
+		;;
+	-*) # Invalid options.
+		printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
+		show_help
+		exit 1
+		;;
+	*) # Default case: If no more options then break out of the loop.
+		break ;;
 	esac
 done
 
@@ -130,27 +130,27 @@ fi
 # We depend on a container manager let's be sure we have it
 # First we use podman, else docker
 case "${container_manager}" in
-	autodetect)
-		if command -v podman > /dev/null; then
-			container_manager="podman"
-		elif command -v docker > /dev/null; then
-			container_manager="docker"
-		fi
-		;;
-	podman)
+autodetect)
+	if command -v podman >/dev/null; then
 		container_manager="podman"
-		;;
-	docker)
+	elif command -v docker >/dev/null; then
 		container_manager="docker"
-		;;
-	*)
-		printf >&2 "Invalid input %s.\n" "${container_manager}"
-		printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
-		;;
+	fi
+	;;
+podman)
+	container_manager="podman"
+	;;
+docker)
+	container_manager="docker"
+	;;
+*)
+	printf >&2 "Invalid input %s.\n" "${container_manager}"
+	printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
+	;;
 esac
 
 # Be sure we have a container manager to work with.
-if ! command -v "${container_manager}" > /dev/null; then
+if ! command -v "${container_manager}" >/dev/null; then
 	# Error: we need at least one between docker or podman.
 	printf >&2 "Missing dependency: we need a container manager.\n"
 	printf >&2 "Please install one of podman or docker.\n"
@@ -173,9 +173,9 @@ fi
 # List containers using custom format that inclused MOUNTS
 # we do this as we can detect the custom mounts done by distrobox to distringuish
 # between a normal podman or docker container and a distrobox one.
-container_list=$( ${container_manager} ps -a --no-trunc --format \
+container_list=$(${container_manager} ps -a --no-trunc --format \
 	"{{.ID}}|{{.Image}}|{{.Names}}|{{.State}}|{{.Labels}}{{.Mounts}}")
-printf  "%-12s | %-20s | %-30s | %-30s\n" "ID" "NAME" "STATUS" "IMAGE"
+printf "%-12s | %-20s | %-30s | %-30s\n" "ID" "NAME" "STATUS" "IMAGE"
 IFS='
 '
 
@@ -183,7 +183,7 @@ IFS='
 GREEN=""
 YELLOW=""
 CLEAR=""
-if [ -t 1 ] && [ "${no_color}" -ne 1 ] ; then
+if [ -t 1 ] && [ "${no_color}" -ne 1 ]; then
 	# we're in a tty, use colors
 	GREEN='\033[32m'
 	YELLOW='\033[33m'
