enter: add docker support. First check if we have podman, then docker, else error. Add `--headless` flag. This is useful for exported app or services to not instantiate a TTY if not needed. This also is a work around for docker not being able to instantiate a TTY correctly if launched via a non-terminal command (eg: desktop apps) Also move log level up in the command so it is compatible with both container managers.

diff --git a/distrobox-enter b/distrobox-enter
--- a/distrobox-enter
+++ b/distrobox-enter
@@ -10,6 +10,7 @@ trap '[ "$?" -ne 0 ] && printf "\nAn error occurred\n"' EXIT
 # Defaults
 container_command="${SHELL:-"bash"} -l"
 container_name="fedora-toolbox-35"
+headless=0
 verbose=0
 version="distrobox_version_placeholder"
 
@@ -35,6 +36,7 @@ Options:
 
 	--name/-n:		name for the distrobox						default: fedora-toolbox-35
 	--/-e:			end arguments execute the rest as command to execute at login	default: bash -l
+	--headless/-H:		do not instantiate a tty
 	--help/-h:		show this message
 	--verbose/-v:		show more verbosity
 	--version/-V:		show version
@@ -52,6 +54,10 @@ while :; do
 	-v | --verbose)
 		shift
 		verbose=1
+		;;
+	-H | --headless)
+		shift
+		headless=1
 		;;
 	-V | --version)
 		printf "distrobox: %s\n" "${version}"
@@ -81,27 +87,37 @@ if [ "${verbose}" -ne 0 ]; then
 	set -o xtrace
 fi
 
-# We depend on podman let's be sure we have it.
-if ! command -v podman >/dev/null; then
-	printf >&2 "Missing dependency: podman\n"
+# We depend on a container manager let's be sure we have it
+# First we use podman, else docker
+container_manager="podman"
+if ! command -v podman >/dev/null && command -v docker >/dev/null; then
+	container_manager="docker"
+elif ! command -v podman >/dev/null && ! command -v docker >/dev/null; then
+	printf >&2 "Missing dependency: we need a container manager\n."
+	printf >&2 "Please install one of podman or docker.\n"
 	exit 127
 fi
 
-# Generate Podman command to execute.
+# Generate Podman or Docker command to execute.
 # Arguments:
 #   None
 # Outputs:
-#   prints the podman command to enter the distrobox container
+#   prints the podman or docker command to enter the distrobox container
 generate_command() {
-	result_command="podman exec"
-	# add podman verbose if -v is specified
+	result_command="${container_manager}"
+	# add  verbose if -v is specified
 	if [ "${verbose}" -ne 0 ]; then
 		result_command="${result_command} --log-level debug"
 	fi
+	result_command="${result_command} exec"
 	result_command="${result_command}
-		--interactive
-		--tty
 		--user=${USER}"
+
+	if [ "${headless}" -eq 0 ]; then
+		result_command="${result_command}
+			--interactive
+			--tty"
+	fi
 	# Entering container using our user and workdir.
 	# Start container from working directory. Else default to home. Else do /.
 	# pass distrobox-enter path, it will be used in the distrobox-export tool.
@@ -129,7 +145,7 @@ generate_command() {
 }
 
 # Does the container exists?
-if ! podman ps -a | grep -qE "(^| )${container_name}( |$)"; then
+if ! "${container_manager}" ps -a | grep -qE "(^| )${container_name}( |$)"; then
 	# If not, prompt to create it first
 	printf >&2 "Cannot find container %s, does it exist?\n" "${container_name}"
 	printf >&2 "\nTry running first:\n"
@@ -138,16 +154,16 @@ if ! podman ps -a | grep -qE "(^| )${container_name}( |$)"; then
 fi
 
 # If the container is not already running, we need to start if first
-if ! podman ps | grep -qE "(^| )${container_name}( |$)"; then
+if ! "${container_manager}" ps | grep -qE "(^| )${container_name}( |$)"; then
 	# If container is not running, start it first
 	# Here, we save the timestamp before launching the start command, so we can
 	# be sure we're working with this very same session of logs later.
 	log_timestamp="$(date +%FT%T.%N%:z)"
-	podman start "${container_name}" >/dev/null
+	"${container_manager}" start "${container_name}" >/dev/null
 
 	printf >&2 "Starting container %s\n" "${container_name}"
 	printf >&2 "run this command to follow along:\n"
-	printf >&2 "\tpodman logs -f %s\n" "${container_name}"
+	printf >&2 "\t%s logs -f %s\n" "${container_manager}" "${container_name}"
 
 	# Wait for container to start successfully.
 	# We will probe the container logs every 1s to check if we have either:
@@ -155,12 +171,12 @@ if ! podman ps | grep -qE "(^| )${container_name}( |$)"; then
 	#
 	# In the end, print eventual Warnings that occurred.
 	while :; do
-		podman_log="$(podman logs -t -n \
+		container_manager_log="$("${container_manager}" logs -t \
 			--since "${log_timestamp}" \
 			"${container_name}" 2>/dev/null)"
-		case "${podman_log}" in
+		case "${container_manager_log}" in
 		*"Error"*)
-			printf >&2 "%s\n" "${podman_log}"
+			printf >&2 "%s\n" "${container_manager_log}"
 			exit 1
 			;;
 		*"container_setup_done"*)
@@ -174,7 +190,7 @@ if ! podman ps | grep -qE "(^| )${container_name}( |$)"; then
 	done
 	printf >&2 "\ndone!\n"
 	# Print eventual warnings in the log.
-	podman logs -t -n \
+	"${container_manager}" logs -t \
 		--since "${log_timestamp}" \
 		"${container_name}" 2>/dev/null | grep "Warning" >&2 || :
 fi
