Add --host-sudo-program to exporting

diff --git a/distrobox-export b/distrobox-export
--- a/distrobox-export
+++ b/distrobox-export
@@ -42,6 +42,7 @@ extra_flags=""
 host_home="${DISTROBOX_HOST_HOME:-"${HOME}"}"
 is_sudo=0
 sudo_program=""
+host_sudo_program=""
 rootful=""
 verbose=0
 version="1.3.2"
@@ -80,10 +81,14 @@ Options:
 				Defaults to (on \$container_name)
 	--export-path/-ep:	path where to export the binary
 	--extra-flags/-ef:	extra flags to add to the command
-	--sudo/-S:		specify if the exported item should be ran as sudo (note: if using a program other than 'sudo' for root privileges on
-				the host is necessary, refer to --sudo-program)
-	--sudo-program		when used with --sudo, specifies a program other than the default 'sudo' with which to launch the exported app
-				with root privileges (common options include 'pkexec' for a graphical root authentication prompt, 'doas', and so on)
+	--sudo/-S:		specify if the exported item should be run as sudo (refer to --sudo-program if sudo is
+				not available in the container or not desired)
+	--sudo-program:		when used with --sudo, specifies a program other than the default 'sudo' with which to launch the exported app
+				with root privileges inside this container (common options include 'pkexec' for a graphical root authentication prompt,
+				'doas', and so on)
+	--host-sudo-program:		if this container is rootful, then this parameter specifies the program that should be used
+				in the host to enter this container with root privileges when launching the exported app/service/binary,
+				other than the default 'sudo' (such as 'pkexec' for a graphical authentication prompt)
 	--help/-h:		show this message
 	--verbose/-v:		show more verbosity
 	--version/-V:		show version
@@ -141,6 +146,13 @@ while :; do
 				shift
 			fi
 			;;
+		--host-sudo-program)
+			if [ -n "$2" ]; then
+				host_sudo_program="$2"
+				shift
+				shift
+			fi
+			;;
 		-el | --export-label)
 			if [ -n "$2" ]; then
 				exported_app_label="$2"
@@ -191,7 +203,11 @@ fi
 
 # Check if we're in a rootful or rootless container.
 if grep -q "rootless=0" /run/.containerenv 2> /dev/null; then
-	rootful="--root"
+	if [ -n "${host_sudo_program}" ]; then # use the specified sudo program on the host
+		rootful="--root --sudo-program '${host_sudo_program}'"
+	else # use sudo by default
+		rootful="--root"
+	fi
 fi
 
 # We're working with HOME, so we must run as USER, not as root.
@@ -225,7 +241,8 @@ if [ -n "${exported_bin}" ] && [ -z "${dest_path}" ]; then
 	exit 2
 fi
 
-# If --sudo-program was specified, ensure --sudo was also given
+# If --sudo-program was specified, ensure --sudo was also given - OK to check, because 'sudo_program'
+# isn't read from config files or env
 if [ "${is_sudo}" -eq 0 ] && [ -n "${sudo_program}" ]; then
 	printf >&2 "Error: The option --sudo-program may only be used together\n"
 	printf >&2 "with --sudo."
@@ -236,6 +253,16 @@ fi
 # "sudo" as the sudo program.
 if [ "${is_sudo}" -ne 0 ] && [ -z "${sudo_program}" ]; then
 	sudo_program="sudo"
+fi
+
+# If a custom sudo program was specified, ensure it exists inside the container
+if [ -n "${sudo_program}" ] && ! command -v "${sudo_program}" > /dev/null; then
+	printf >&2 "Invalid sudo program specified for usage in invoking\n"
+	printf >&2 "the exported app/service/binary as root inside\n"
+	printf >&2 "the container. Please specify a command that exists\n"
+	printf >&2 "inside the container for the --sudo-program option, or\n"
+	printf >&2 "do not specify it to use the default 'sudo'.\n"
+	exit 2
 fi
 
 # We can assume this as we set it the same as container name during creation.
