init: reintroduce themes and icon integration, Fix #15

diff --git a/distrobox-init b/distrobox-init
--- a/distrobox-init
+++ b/distrobox-init
@@ -245,6 +245,36 @@ fi
 passwd --delete "${container_user_name}"
 passwd --delete root
 
+# Find all hosts icons and link them in home. Exclude hicolor as that will be
+# used to export applications later.
+host_icons="$(find /run/host/usr/share/icons -maxdepth 1 -type d -not -path "*hicolor" | tail -n +2)"
+# ensure dest folder exists.
+if ! mkdir -p "${HOME}/.local/share/icons"; then
+	printf "Warning: could not create icons folder to export.\n"
+	printf "Warning: disabling icons integration.\n"
+fi
+for host_icon in ${host_icons}; do
+	# check if it already exists first.
+	if [ ! -d "${HOME}/.local/share/icons/$(basename "${host_icon}")" ]; then
+		ln -s "${host_icon}" "${HOME}/.local/share/icons/$(basename "${host_icon}")"
+	fi
+done
+
+# Find all hosts themes and link them in home. Exclude hicolor as that will be
+# used to export applications later.
+host_themes="$(find /run/host/usr/share/themes -maxdepth 1 -type d | tail -n +2)"
+# ensure dest folder exists.
+if ! mkdir -p "${HOME}/.local/share/themes"; then
+	printf "Warning: could not create themes folder to export.\n"
+	printf "Warning: disabling theme integration.\n"
+fi
+for host_theme in ${host_themes}; do
+	# check if it already exists first.
+	if [ ! -d "${HOME}/.local/share/themes/$(basename "${host_theme}")" ]; then
+		ln -s "${host_theme}" "${HOME}/.local/share/themes/$(basename "${host_theme}")"
+	fi
+done
+
 printf "container_setup_done\n"
 # Keepalive loop
 sleep infinity
