enter: improve logging steps
Use a new log every 1s, do not rely on another logging process via fifo
This should be a bit more resilient when you don't get logs for some
time

Fix #286

Signed-off-by: 89luca89 <luca.dimaio1@gmail.com>

diff --git a/distrobox-enter b/distrobox-enter
--- a/distrobox-enter
+++ b/distrobox-enter
@@ -403,39 +403,36 @@ if [ "${container_status}" != "running" ]; then
 		exit 1
 	fi
 
-	# Wait for container to finish setup successfully.
-	rm -f "/tmp/.${container_name}.fifo" && mkfifo "/tmp/.${container_name}.fifo"
-	${container_manager} logs \
-		--since "${log_timestamp}" \
-		-f "${container_name}" 2> /dev/null > "/tmp/.${container_name}.fifo" &
-	container_log_pid="$!"
-
 	printf >&2 "%-40s\t" " Starting container..."
-	while IFS= read -r line; do
-		# Check if the container is going in error status at any time during the first init
-		case "${line}" in
-			*"Error"*)
-				printf >&2 "\033[31m %s\n\033[0m" "${line}"
-				exit 1
-				;;
-			*"Warning"*)
-				printf >&2 "\n\033[33m %s\033[0m" "${line}"
-				;;
-			*"distrobox:"*)
-				printf >&2 "\033[32m [ OK ]\n\033[0m%-40s\t" "$(echo "${line}" | cut -d':' -f2-)"
-				;;
-			*"container_setup_done"*)
-				printf >&2 "\033[32m [ OK ]\n\033[0m"
-				break
-				;;
-			*) ;;
-		esac
-	done < "/tmp/.${container_name}.fifo"
+	while true; do
+		${container_manager} logs --since "${log_timestamp}" "${container_name}" 2> /dev/null > "/tmp/.${container_name}.fifo"
+		# read logs from log_timestamp to now, line by line
+		while IFS= read -r line; do
+			case "${line}" in
+				*"Error"*)
+					printf >&2 "\033[31m %s\n\033[0m" "${line}"
+					exit 1
+					;;
+				*"Warning"*)
+					printf >&2 "\n\033[33m %s\033[0m" "${line}"
+					;;
+				*"distrobox:"*)
+					printf >&2 "\033[32m [ OK ]\n\033[0m%-40s\t" "$(echo "${line}" | grep "distrobox" | cut -d':' -f2-)"
+					;;
+				*"container_setup_done"*)
+					printf >&2 "\033[32m [ OK ]\n\033[0m"
+					break 2
+					;;
+				*) ;;
+			esac
+		done < "/tmp/.${container_name}.fifo"
+		# Register new timestamp where to start logs from.
+		log_timestamp="$(date +%FT%T.%N%:z)"
 
-	# Kill log process, cleanup fifo
-	kill -INT "${container_log_pid}"
+		sleep 1
+	done
+	# cleanup fifo
 	rm -f "/tmp/.${container_name}.fifo"
-
 	printf >&2 "\nContainer Setup Complete!\n"
 fi
 
