enter: improve fist-start logging and show user some progress
Signed-off-by: 89luca89 <luca.dimaio1@gmail.com>

diff --git a/distrobox-enter b/distrobox-enter
--- a/distrobox-enter
+++ b/distrobox-enter
@@ -27,7 +27,7 @@
 #	DBX_CONTAINER_NAME
 #	DBX_CONTAINER_MANAGER
 
-trap '[ "$?" -ne 0 ] && printf "\nAn error occurred\n"' EXIT
+trap '[ "$?" -ne 0 ] && printf "\nAn error occurred\n" && rm -f "/tmp/.*.fifo"' EXIT
 
 # Dont' run this command as sudo.
 if [ "$(id -u)" -eq 0 ]; then
@@ -382,52 +382,57 @@ if [ "${container_status}" != "running" ]; then
 	# If container is not running, start it first
 	# Here, we save the timestamp before launching the start command, so we can
 	# be sure we're working with this very same session of logs later.
-	log_timestamp="$(date +%FT%T.%N%:z)"
-	${container_manager} start "${container_name}" > /dev/null
 
+	printf >&2 "Container %s is not runnung.\n" "${container_name}"
 	printf >&2 "Starting container %s\n" "${container_name}"
 	printf >&2 "run this command to follow along:\n\n"
-	printf >&2 "%s logs -f %s\n" "${container_manager}" "${container_name}"
+	printf >&2 "%s logs -f %s\n\n" "${container_manager}" "${container_name}"
 
-	# Wait for container to start successfully.
-	# We will probe the container logs every 1s to check if we have either:
-	# Error or container_setup_done
-	#
-	# In the end, print eventual Warnings that occurred.
-	while :; do
+	${container_manager} start "${container_name}" > /dev/null
+	# Check if the container is going in error status earlier than the
+	# entrypoint
+	if [ "$(${container_manager} inspect \
+		--type container "${container_name}" \
+		--format "{{.State.Status}}")" != "running" ]; then
 
+		printf >&2 "\033[31m Error: could not start entrypoint.\n\033[0m"
+		container_manager_log="$(${container_manager} logs "${container_name}")"
+		printf >&2 "%s\n" "${container_manager_log}"
+		exit 1
+	fi
+
+	# Wait for container to finish setup successfully.
+	rm -f "/tmp/.${container_name}.fifo" && mkfifo "/tmp/.${container_name}.fifo"
+	${container_manager} logs -f "${container_name}" 2> /dev/null > "/tmp/.${container_name}.fifo" &
+	container_log_pid="$!"
+
+	printf >&2 "%-40s\t" " Starting container..."
+	while IFS= read -r line; do
 		# Check if the container is going in error status at any time during the first init
-		if [ "$(${container_manager} inspect \
-			--type container "${container_name}" \
-			--format "{{.State.Status}}")" != "running" ]; then
-
-			container_manager_log="$(${container_manager} logs "${container_name}")"
-			printf >&2 "%s\n" "${container_manager_log}"
-			exit 1
-		fi
-
-		container_manager_log="$(${container_manager} logs -t \
-			--since "${log_timestamp}" \
-			"${container_name}" 2> /dev/null)"
-		case "${container_manager_log}" in
+		case "${line}" in
 			*"Error"*)
-				printf >&2 "%s\n" "${container_manager_log}"
+				printf >&2 "\033[31m %s\n\033[0m" "${line}"
 				exit 1
 				;;
+			*"Warning"*)
+				printf >&2 "\n\033[33m %s\033[0m" "${line}"
+				;;
+			*"distrobox:"*)
+				printf >&2 "\033[32m [ OK ]\n\033[0m%-40s\t" "$(echo "${line}" | cut -d':' -f2-)"
+				;;
 			*"container_setup_done"*)
+				printf >&2 "\033[32m [ OK ]\n\033[0m"
 				break
 				;;
-			*)
-				printf >&2 "."
-				sleep 1
-				;;
+			*) ;;
 		esac
-	done
-	printf >&2 "\ndone!\n"
-	# Print eventual warnings in the log.
-	${container_manager} logs -t \
-		--since "${log_timestamp}" \
-		"${container_name}" 2> /dev/null | grep "Warning" >&2 || :
+	done < "/tmp/.${container_name}.fifo"
+
+	# Kill log process, cleanup fifo
+	kill -INT "${container_log_pid}"
+	rm -f "/tmp/.${container_name}.fifo"
+
+	printf >&2 "Container Setup Complete!\n"
 fi
 
 # Generate the exec command and run it
diff --git a/distrobox-init b/distrobox-init
--- a/distrobox-init
+++ b/distrobox-init
@@ -115,7 +115,7 @@ while :; do
 			break
 			;;
 		-*) # Invalid options.
-			printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
+			printf >&2 "Error: Invalid flag '%s'\n\n" "$1"
 			show_help
 			exit 1
 			;;
@@ -195,7 +195,7 @@ mount_bind() (
 
 	return 0
 )
-
+printf "distrobox: Installing basic packages...\n"
 # Extract shell name from the $SHELL environment variable
 # If not present as package in the container, we want to install it.
 shell_pkg="$(basename "${SHELL:-"bash"}")"
@@ -437,6 +437,8 @@ if ! command -v find || ! command -v mount || ! command -v passwd ||
 	fi
 
 fi
+
+printf "distrobox: Setting up read-only mounts...\n"
 # We'll also bind mount in READ-ONLY useful directories from the host
 HOST_MOUNTS_RO="
 	/var/lib/flatpak
@@ -446,6 +448,7 @@ for host_mount_ro in ${HOST_MOUNTS_RO}; do
 	mount_bind /run/host"${host_mount_ro}" "${host_mount_ro}" ro
 done
 
+printf "distrobox: Setting up read-write mounts...\n"
 # We'll also bind mount READ-WRITE useful mountpoints to pass external drives and libvirt from
 # the host to the container
 HOST_MOUNTS="
@@ -471,6 +474,7 @@ for host_mount in ${HOST_MOUNTS}; do
 	fi
 done
 
+printf "distrobox: Setting up host's sockets integration...\n"
 # Find all the user's socket and mount them inside the container
 # this will allow for continuity of functionality between host and container
 #
@@ -494,6 +498,7 @@ for host_socket in ${host_sockets}; do
 	fi
 done
 
+printf "distrobox: Setting up package manager exceptions...\n"
 # In case of an RPM distro, we can specify that our bind_mount directories
 # are in fact net shares. This prevents conflicts during package installations.
 if [ -d "/usr/lib/rpm/macros.d/" ]; then
@@ -613,6 +618,7 @@ EOF
 
 fi
 
+printf "distrobox: Setting up sudo...\n"
 mkdir -p /etc/sudoers.d
 # Do not check fqdn when doing sudo, it will not work anyways
 if ! grep -q 'Defaults !fqdn' /etc/sudoers.d/sudoers; then
@@ -623,6 +629,7 @@ if ! grep -q "${container_user_name} ALL = (root) NOPASSWD:ALL" /etc/sudoers.d/s
 	printf "%s ALL = (root) NOPASSWD:ALL\n" "${container_user_name}" >> /etc/sudoers.d/sudoers
 fi
 
+printf "distrobox: Setting up groups...\n"
 # If not existing, ensure we have a group for our user.
 if ! grep -q "^${container_user_name}:" /etc/group; then
 	if ! groupadd --force --gid "${container_user_gid}" "${container_user_name}"; then
@@ -631,6 +638,8 @@ if ! grep -q "^${container_user_name}:" /etc/group; then
 		printf "%s:x:%s:" "${container_user_name}" "${container_user_gid}" >> /etc/group
 	fi
 fi
+
+printf "distrobox: Setting up users...\n"
 # Let's add our user to the container. if the user already exists, enforce properties.
 if ! grep -q "^${container_user_name}:" /etc/passwd; then
 	if ! useradd \
@@ -693,6 +702,7 @@ if [ -d "/etc/skel" ]; then
 	done
 fi
 
+printf "distrobox: Integrating host's themes, icons, fonts...\n"
 # Themes and icons integration works using a bind mount inside the container
 # of the host's themes and icons directory. This ensures that the host's home will
 # not be littered with files and directories and broken symlinks.
@@ -720,6 +730,7 @@ if ! mount_bind "/run/host/usr/share/fonts" "${container_user_home}/.local/share
 	printf "Warning: Fonts integration with the host is disabled.\n"
 fi
 
+printf "distrobox: Executing init hooks...\n"
 # execute eventual init hooks if specified
 # shellcheck disable=SC2086
 eval ${init_hook}
@@ -757,6 +768,7 @@ else
 	# some of this directories are needed by
 	# the init system. If they're mounts, there might
 	# be problems. Let's unmount them.
+	printf "distrobox: Setting up init system...\n"
 	HOST_MOUNTS_RO_INIT="
 		/run/systemd/journal
 		/run/systemd/seats
@@ -769,5 +781,6 @@ else
 		if mountpoint "${host_mount}"; then umount "${host_mount}"; fi
 	done
 	# Now we can launch init
+	printf "distrobox: Firing up init system...\n"
 	exec /sbin/init
 fi
