support environment variables to change defaults (#207)
* support environment variables to change defaults
* CI: test both podman and docker using new ENV variable

Implement use of environment variables to change defaults like:

 - container manager
 - default image to use
 - default name to use
 - interactivity

Variables will be respectively:

- DBX_CONTAINER_MANAGER
- DBX_CONTAINER_IMAGE
- DBX_CONTAINER_NAME
- DBX_NON_INTERACTIVE

This work opens also support for configuration rc-style files, in order of 
importance:

- /usr/share/distrobox/distrobox.conf
- /etc/distrobox/distrobox.conf
- ${HOME}/.config/distrobox/distrobox.conf
- ${HOME}/.distroboxrc

diff --git a/distrobox-create b/distrobox-create
--- a/distrobox-create
+++ b/distrobox-create
@@ -23,7 +23,9 @@
 #	HOME
 #	USER
 # Optional env variables:
+#	DBX_CONTAINER_CUSTOM_HOME
 #	DBX_CONTAINER_IMAGE
+#	DBX_CONTAINER_MANAGER
 #	DBX_CONTAINER_NAME
 #	DBX_NON_INTERACTIVE
 
@@ -41,16 +43,18 @@ fi
 
 # Defaults
 container_clone=""
-container_image="${DBX_CONTAINER_IMAGE:-""}"
+container_image=""
 container_image_default="registry.fedoraproject.org/fedora-toolbox:35"
 container_init_hook=""
+container_manager="autodetect"
 container_manager_additional_flags=""
-container_name="${DBX_CONTAINER_NAME:-""}"
+container_name=""
 container_user_custom_home=""
 container_user_gid="$(id -rg)"
 container_user_home="${HOME:-"/"}"
 container_user_name="${USER}"
 container_user_uid="$(id -ru)"
+non_interactive=0
 # Use cd + dirname + pwd so that we do not have relative paths in mount points
 # We're not using "realpath" here so that symlinks are not resolved this way
 # "realpath" would break situations like Nix or similar symlink based package
@@ -61,11 +65,29 @@ distrobox_export_path="$(cd "$(dirname "${0}")" && pwd)/distrobox-export"
 # in PATH for them.
 [ ! -e "${distrobox_entrypoint_path}" ] && distrobox_entrypoint_path="$(command -v distrobox-init)"
 [ ! -e "${distrobox_export_path}" ] && distrobox_export_path="$(command -v distrobox-export)"
-non_interactive="${DBX_NON_INTERACTIVE:-0}"
 dryrun=0
 init=0
 verbose=0
 version="1.2.14"
+
+# Source configuration files, this is done in an hierarchy so local files have
+# priority over system defaults
+# leave priority to environment variables.
+config_files="
+	/usr/share/distrobox/distrobox.conf
+	/etc/distrobox/distrobox.conf
+	${HOME}/.config/distrobox/distrobox.conf
+	${HOME}/.distroboxrc
+"
+for config_file in ${config_files}; do
+	# shellcheck disable=SC1090
+	[ -e "${config_file}" ] && . "${config_file}"
+done
+[ -n "${DBX_CONTAINER_CUSTOM_HOME}" ] && container_user_custom_home="${DBX_CONTAINER_CUSTOM_HOME}"
+[ -n "${DBX_CONTAINER_IMAGE}" ] && container_image="${DBX_CONTAINER_IMAGE}"
+[ -n "${DBX_CONTAINER_MANAGER}" ] && container_manager="${DBX_CONTAINER_MANAGER}"
+[ -n "${DBX_CONTAINER_NAME}" ] && container_name="${DBX_CONTAINER_NAME}"
+[ -n "${DBX_NON_INTERACTIVE}" ] && non_interactive="${DBX_NON_INTERACTIVE}"
 
 # Print usage to stdout.
 # Arguments:
@@ -199,7 +221,7 @@ while :; do
 	*) # Default case: If no more options then break out of the loop.
 		# If we have a flagless option and container_name is not specified
 		# then let's accept argument as container_name
-		if [ -z "${container_name}" ] && [ -n "$1" ]; then
+		if [ -n "$1" ]; then
 			container_name="$1"
 			shift
 		else
@@ -242,22 +264,40 @@ fi
 
 # We depend on a container manager let's be sure we have it
 # First we use podman, else docker
-container_manager="podman"
+case "${container_manager}" in
+autodetect)
+	if command -v podman >/dev/null; then
+		container_manager="podman"
+	elif command -v docker >/dev/null; then
+		container_manager="docker"
+	else
+		container_manager="not_found"
+	fi
+	;;
+podman)
+	container_manager="podman"
+	;;
+docker)
+	container_manager="docker"
+	;;
+*)
+	printf >&2 "Invalid input %s.\n" "${container_manager}"
+	printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
+	container_manager="not_found"
+	;;
+esac
+
 # Be sure we have a container manager to work with.
 if ! command -v "${container_manager}" >/dev/null; then
-	# If no podman, try docker.
-	container_manager="docker"
-	if ! command -v docker >/dev/null; then
-		# Error: we need at least one between docker or podman.
-		printf >&2 "Missing dependency: we need a container manager.\n"
-		printf >&2 "Please install one of podman or docker.\n"
-		printf >&2 "You can follow the documentation on:\n"
-		printf >&2 "\tman distrobox-compatibility\n"
-		printf >&2 "or:\n"
-		printf >&2 "\thttps://github.com/89luca89/distrobox/blob/main/docs/compatibility.md\n"
-		if [ "${dryrun}" -eq 0 ]; then
-			exit 127
-		fi
+	# Error: we need at least one between docker or podman.
+	printf >&2 "Missing dependency: we need a container manager.\n"
+	printf >&2 "Please install one of podman or docker.\n"
+	printf >&2 "You can follow the documentation on:\n"
+	printf >&2 "\tman distrobox-compatibility\n"
+	printf >&2 "or:\n"
+	printf >&2 "\thttps://github.com/89luca89/distrobox/blob/main/docs/compatibility.md\n"
+	if [ "${dryrun}" -eq 0 ]; then
+		exit 127
 	fi
 fi
 # add  verbose if -v is specified
diff --git a/distrobox-enter b/distrobox-enter
--- a/distrobox-enter
+++ b/distrobox-enter
@@ -25,6 +25,7 @@
 #	SHELL
 # Optional env variables:
 #	DBX_CONTAINER_NAME
+#	DBX_CONTAINER_MANAGER
 
 trap '[ "$?" -ne 0 ] && printf "\nAn error occurred\n"' EXIT
 
@@ -40,13 +41,14 @@ fi
 
 # Defaults
 container_command="${SHELL:-"bash"}"
+container_manager="autodetect"
+container_name="fedora-toolbox-35"
 # Work around for shells that are not in the container's file system, nor PATH.
 # For example in hosts that do not follow FHS, like NixOS or for shells in custom
 # exotic paths.
 container_command="$(basename "${container_command}") -l"
 container_manager_additional_flags=""
-container_name="${DBX_CONTAINER_NAME:-""}"
-container_name_default="fedora-toolbox-35"
+
 # Use cd + dirname + pwd so that we do not have relative paths in mount points
 # We're not using "realpath" here so that symlinks are not resolved this way
 # "realpath" would break situations like Nix or similar symlink based package
@@ -56,6 +58,22 @@ dryrun=0
 headless=0
 verbose=0
 version="1.2.14"
+
+# Source configuration files, this is done in an hierarchy so local files have
+# priority over system defaults
+# leave priority to environment variables.
+config_files="
+	/usr/share/distrobox/distrobox.conf
+	/etc/distrobox/distrobox.conf
+	${HOME}/.config/distrobox/distrobox.conf
+	${HOME}/.distroboxrc
+"
+for config_file in ${config_files}; do
+	# shellcheck disable=SC1090
+	[ -e "${config_file}" ] && . "${config_file}"
+done
+[ -n "${DBX_CONTAINER_MANAGER}" ] && container_manager="${DBX_CONTAINER_MANAGER}"
+[ -n "${DBX_CONTAINER_NAME}" ] && container_name="${DBX_CONTAINER_NAME}"
 
 # Print usage to stdout.
 # Arguments:
@@ -133,7 +151,7 @@ while :; do
 	*) # Default case: If no more options then break out of the loop.
 		# If we have a flagless option and container_name is not specified
 		# then let's accept argument as container_name
-		if [ -z "${container_name}" ] && [ -n "$1" ]; then
+		if [ -n "$1" ]; then
 			container_name="$1"
 			shift
 		else
@@ -152,22 +170,40 @@ fi
 
 # We depend on a container manager let's be sure we have it
 # First we use podman, else docker
-container_manager="podman"
+case "${container_manager}" in
+autodetect)
+	if command -v podman >/dev/null; then
+		container_manager="podman"
+	elif command -v docker >/dev/null; then
+		container_manager="docker"
+	else
+		container_manager="not_found"
+	fi
+	;;
+podman)
+	container_manager="podman"
+	;;
+docker)
+	container_manager="docker"
+	;;
+*)
+	printf >&2 "Invalid input %s.\n" "${container_manager}"
+	printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
+	container_manager="not_found"
+	;;
+esac
+
 # Be sure we have a container manager to work with.
 if ! command -v "${container_manager}" >/dev/null; then
-	# If no podman, try docker.
-	container_manager="docker"
-	if ! command -v docker >/dev/null; then
-		# Error: we need at least one between docker or podman.
-		printf >&2 "Missing dependency: we need a container manager.\n"
-		printf >&2 "Please install one of podman or docker.\n"
-		printf >&2 "You can follow the documentation on:\n"
-		printf >&2 "\tman distrobox-compatibility\n"
-		printf >&2 "or:\n"
-		printf >&2 "\thttps://github.com/89luca89/distrobox/blob/main/docs/compatibility.md\n"
-		if [ "${dryrun}" -eq 0 ]; then
-			exit 127
-		fi
+	# Error: we need at least one between docker or podman.
+	printf >&2 "Missing dependency: we need a container manager.\n"
+	printf >&2 "Please install one of podman or docker.\n"
+	printf >&2 "You can follow the documentation on:\n"
+	printf >&2 "\tman distrobox-compatibility\n"
+	printf >&2 "or:\n"
+	printf >&2 "\thttps://github.com/89luca89/distrobox/blob/main/docs/compatibility.md\n"
+	if [ "${dryrun}" -eq 0 ]; then
+		exit 127
 	fi
 fi
 # Small performance optimization, using podman socket shaves
@@ -187,10 +223,6 @@ fi
 # add  verbose if -v is specified
 if [ "${verbose}" -ne 0 ]; then
 	container_manager="${container_manager} --log-level debug"
-fi
-# Set default container_name if no one is specified.
-if [ -z "${container_name}" ]; then
-	container_name="${container_name_default}"
 fi
 
 # Generate Podman or Docker command to execute.
diff --git a/distrobox-list b/distrobox-list
--- a/distrobox-list
+++ b/distrobox-list
@@ -19,6 +19,8 @@
 # along with distrobox; if not, see <http://www.gnu.org/licenses/>.
 
 # POSIX
+# Optional env variables:
+#	DBX_CONTAINER_MANAGER
 
 # Dont' run this command as sudo.
 if [ "$(id -u)" -eq 0 ]; then
@@ -33,6 +35,22 @@ fi
 # Defaults
 verbose=0
 version="1.2.14"
+container_manager="autodetect"
+
+# Source configuration files, this is done in an hierarchy so local files have
+# priority over system defaults
+# leave priority to environment variables.
+config_files="
+	/usr/share/distrobox/distrobox.conf
+	/etc/distrobox/distrobox.conf
+	${HOME}/.config/distrobox/distrobox.conf
+	${HOME}/.distroboxrc
+"
+for config_file in ${config_files}; do
+	# shellcheck disable=SC1090
+	[ -e "${config_file}" ] && . "${config_file}"
+done
+[ -n "${DBX_CONTAINER_MANAGER}" ] && container_manager="${DBX_CONTAINER_MANAGER}"
 
 # Print usage to stdout.
 # Arguments:
@@ -89,23 +107,40 @@ fi
 
 # We depend on a container manager let's be sure we have it
 # First we use podman, else docker
-container_manager="podman"
-# Be sure we have a container manager to work with.
-if ! command -v podman >/dev/null; then
-	# If no podman, try docker.
-	container_manager="docker"
-	if ! command -v docker >/dev/null; then
-		# Error: we need at least one between docker or podman.
-		printf >&2 "Missing dependency: we need a container manager.\n"
-		printf >&2 "Please install one of podman or docker.\n"
-		printf >&2 "You can follow the documentation on:\n"
-		printf >&2 "\tman distrobox-compatibility\n"
-		printf >&2 "or:\n"
-		printf >&2 "\thttps://github.com/89luca89/distrobox/blob/main/docs/compatibility.md\n"
-		exit 127
+case "${container_manager}" in
+autodetect)
+	if command -v podman >/dev/null; then
+		container_manager="podman"
+	elif command -v docker >/dev/null; then
+		container_manager="docker"
+	else
+		container_manager="not_found"
 	fi
-fi
+	;;
+podman)
+	container_manager="podman"
+	;;
+docker)
+	container_manager="docker"
+	;;
+*)
+	printf >&2 "Invalid input %s.\n" "${container_manager}"
+	printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
+	container_manager="not_found"
+	;;
+esac
 
+# Be sure we have a container manager to work with.
+if ! command -v "${container_manager}" >/dev/null; then
+	# Error: we need at least one between docker or podman.
+	printf >&2 "Missing dependency: we need a container manager.\n"
+	printf >&2 "Please install one of podman or docker.\n"
+	printf >&2 "You can follow the documentation on:\n"
+	printf >&2 "\tman distrobox-compatibility\n"
+	printf >&2 "or:\n"
+	printf >&2 "\thttps://github.com/89luca89/distrobox/blob/main/docs/compatibility.md\n"
+	exit 127
+fi
 # add  verbose if -v is specified
 if [ "${verbose}" -ne 0 ]; then
 	container_manager="${container_manager} --log-level debug"
diff --git a/distrobox-rm b/distrobox-rm
--- a/distrobox-rm
+++ b/distrobox-rm
@@ -19,6 +19,10 @@
 # along with distrobox; if not, see <http://www.gnu.org/licenses/>.
 
 # POSIX
+# Optional env variables:
+#	DBX_CONTAINER_MANAGER
+#   DBX_CONTAINER_NAME
+#   DBX_NON_INTERACTIVE
 
 # Dont' run this command as sudo.
 if [ "$(id -u)" -eq 0 ]; then
@@ -31,11 +35,29 @@ if [ "$(id -u)" -eq 0 ]; then
 fi
 
 # Defaults
-container_name="${DB_CONTAINER_NAME:-""}"
+container_manager="autodetect"
+container_name="fedora-toolbox-35"
 force=0
-non_interactive="${DBX_NON_INTERACTIVE:-0}"
+non_interactive=0
 verbose=0
 version="1.2.14"
+
+# Source configuration files, this is done in an hierarchy so local files have
+# priority over system defaults
+# leave priority to environment variables.
+config_files="
+	/usr/share/distrobox/distrobox.conf
+	/etc/distrobox/distrobox.conf
+	${HOME}/.config/distrobox/distrobox.conf
+	${HOME}/.distroboxrc
+"
+for config_file in ${config_files}; do
+	# shellcheck disable=SC1090
+	[ -e "${config_file}" ] && . "${config_file}"
+done
+[ -n "${DBX_CONTAINER_MANAGER}" ] && container_manager="${DBX_CONTAINER_MANAGER}"
+[ -n "${DBX_CONTAINER_NAME}" ] && container_name="${DBX_CONTAINER_NAME}"
+[ -n "${DBX_NON_INTERACTIVE}" ] && non_interactive="${DBX_NON_INTERACTIVE}"
 
 # Print usage to stdout.
 # Arguments:
@@ -99,7 +121,7 @@ while :; do
 	*) # Default case: If no more options then break out of the loop.
 		# If we have a flagless option and container_name is not specified
 		# then let's accept argument as container_name
-		if [ -z "${container_name}" ] && [ -n "$1" ]; then
+		if [ -n "$1" ]; then
 			container_name="$1"
 			shift
 		else
@@ -108,9 +130,6 @@ while :; do
 		;;
 	esac
 done
-# Ensure the foundamental variables are set and not empty, we will not proceed if
-# they are not all set.
-[ -z "${container_name}" ] && printf "Error: Invalid arguments, missing container name\n" && exit 2
 
 set -o errexit
 set -o nounset
@@ -121,21 +140,39 @@ fi
 
 # We depend on a container manager let's be sure we have it
 # First we use podman, else docker
-container_manager="podman"
-# Be sure we have a container manager to work with.
-if ! command -v podman >/dev/null; then
-	# If no podman, try docker.
-	container_manager="docker"
-	if ! command -v docker >/dev/null; then
-		# Error: we need at least one between docker or podman.
-		printf >&2 "Missing dependency: we need a container manager.\n"
-		printf >&2 "Please install one of podman or docker.\n"
-		printf >&2 "You can follow the documentation on:\n"
-		printf >&2 "\tman distrobox-compatibility\n"
-		printf >&2 "or:\n"
-		printf >&2 "\thttps://github.com/89luca89/distrobox/blob/main/docs/compatibility.md\n"
-		exit 127
+case "${container_manager}" in
+autodetect)
+	if command -v podman >/dev/null; then
+		container_manager="podman"
+	elif command -v docker >/dev/null; then
+		container_manager="docker"
+	else
+		container_manager="not_found"
 	fi
+	;;
+podman)
+	container_manager="podman"
+	;;
+docker)
+	container_manager="docker"
+	;;
+*)
+	printf >&2 "Invalid input %s.\n" "${container_manager}"
+	printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
+	container_manager="not_found"
+	;;
+esac
+
+# Be sure we have a container manager to work with.
+if ! command -v "${container_manager}" >/dev/null; then
+	# Error: we need at least one between docker or podman.
+	printf >&2 "Missing dependency: we need a container manager.\n"
+	printf >&2 "Please install one of podman or docker.\n"
+	printf >&2 "You can follow the documentation on:\n"
+	printf >&2 "\tman distrobox-compatibility\n"
+	printf >&2 "or:\n"
+	printf >&2 "\thttps://github.com/89luca89/distrobox/blob/main/docs/compatibility.md\n"
+	exit 127
 fi
 # add  verbose if -v is specified
 if [ "${verbose}" -ne 0 ]; then
