Add --sudo-program option

diff --git a/distrobox-create b/distrobox-create
--- a/distrobox-create
+++ b/distrobox-create
@@ -29,6 +29,7 @@
 #	DBX_CONTAINER_MANAGER
 #	DBX_CONTAINER_NAME
 #	DBX_NON_INTERACTIVE
+#   DBX_SUDO_PROGRAM
 
 trap '[ "$?" -ne 0 ] && printf "\nAn error occurred\n"' EXIT
 
@@ -56,6 +57,7 @@ container_user_home="${HOME:-"/"}"
 container_user_name="${USER}"
 container_user_uid="$(id -ru)"
 non_interactive=0
+distrobox_sudo_program="sudo"
 # Use cd + dirname + pwd so that we do not have relative paths in mount points
 # We're not using "realpath" here so that symlinks are not resolved this way
 # "realpath" would break situations like Nix or similar symlink based package
@@ -97,6 +99,7 @@ done
 [ -n "${DBX_CONTAINER_MANAGER}" ] && container_manager="${DBX_CONTAINER_MANAGER}"
 [ -n "${DBX_CONTAINER_NAME}" ] && container_name="${DBX_CONTAINER_NAME}"
 [ -n "${DBX_NON_INTERACTIVE}" ] && non_interactive="${DBX_NON_INTERACTIVE}"
+[ -n "${DBX_SUDO_PROGRAM}" ] && distrobox_sudo_program="${DBX_SUDO_PROGRAM}"
 
 # Print usage to stdout.
 # Arguments:
@@ -127,7 +130,10 @@ Options:
 	--pull/-p:		pull the image even if it exists locally (implies --yes)
 	--yes/-Y:		non-interactive, pull images without asking
 	--root/-r:		launch podman/docker with root privileges. Note that if you need root this is the preferred
-				way over "sudo distrobox"
+				way over "sudo distrobox" (note: if using a program other than 'sudo' for root privileges is necessary,
+				refer to --sudo-program)
+	--sudo-program		when used with --root, specifies a program other than the default 'sudo' with which to launch podman/docker
+				with root privileges (common options include 'pkexec' for a graphical root authentication prompt, 'doas', and so on)
 	--clone/-c:		name of the distrobox container to use as base for a new container
 				this will be useful to either rename an existing distrobox or have multiple copies
 				of the same environment.
@@ -174,6 +180,13 @@ while :; do
 		-r | --root)
 			shift
 			rootful=1
+			;;
+		--sudo-program)
+			if [ -n "$2" ]; then
+				distrobox_sudo_program="$2"
+				shift
+				shift
+			fi
 			;;
 		-I | --init)
 			shift
@@ -336,9 +349,18 @@ if [ "${verbose}" -ne 0 ]; then
 	container_manager="${container_manager} --log-level debug"
 fi
 
-# prepend sudo if we want podman or docker to be rootful
+# prepend sudo (or the specified sudo program) if we want podman or docker to be rootful
 if [ "${rootful}" -ne 0 ]; then
-	container_manager="sudo ${container_manager}"
+
+	# make sure the given sudo program exists
+	if ! command -v "${distrobox_sudo_program}" > /dev/null; then
+		printf >&2 "Invalid sudo program specified for usage in\n"
+		printf >&2 "managing rootful containers. Please specify\n"
+		printf >&2 "a valid command for the sudo program option, or\n"
+		printf >&2 "do not specify it to use the default 'sudo'."
+		exit 127
+	fi
+	container_manager="${distrobox_sudo_program} ${container_manager}"
 fi
 
 # Clone a container as a snapshot.
@@ -572,7 +594,11 @@ if ${container_manager} inspect --type container "${container_name}" > /dev/null
 	printf "Distrobox named '%s' already exists.\n" "${container_name}"
 	printf "To enter, run:\n\n"
 	if [ "${rootful}" -ne 0 ]; then
-		printf "distrobox-enter --root %s\n\n" "${container_name}"
+		if [ "${distrobox_sudo_program}" != "sudo" ]; then  # if a custom sudo program was specified, indicate it in the suggested command
+			printf "distrobox-enter --root --sudo-program '%s' %s\n\n" "${distrobox_sudo_program}" "${container_name}"
+		else  # using sudo by default
+			printf "distrobox-enter --root %s\n\n" "${container_name}"
+		fi
 	else
 		printf "distrobox-enter %s\n\n" "${container_name}"
 	fi
@@ -628,7 +654,11 @@ if eval ${cmd} > /dev/null; then
 	printf >&2 "\033[32m [ OK ]\n\033[0mDistrobox '%s' successfully created.\n" "${container_name}"
 	printf >&2 "To enter, run:\n\n"
 	if [ "${rootful}" -ne 0 ]; then
-		printf "distrobox enter --root %s\n\n" "${container_name}"
+		if [ "${distrobox_sudo_program}" != "sudo" ]; then  # if a custom sudo program was specified, indicate it in the suggested command
+			printf "distrobox-enter --root --sudo-program '%s' %s\n\n" "${distrobox_sudo_program}" "${container_name}"
+		else  # using sudo by default
+			printf "distrobox-enter --root %s\n\n" "${container_name}"
+		fi
 	else
 		printf "distrobox enter %s\n\n" "${container_name}"
 	fi
diff --git a/distrobox-enter b/distrobox-enter
--- a/distrobox-enter
+++ b/distrobox-enter
@@ -27,6 +27,7 @@
 #	DBX_CONTAINER_MANAGER
 #	DBX_CONTAINER_NAME
 #	DBX_SKIP_WORKDIR
+#   DBX_SUDO_PROGRAM
 
 trap '[ "$?" -ne 0 ] && printf "\nAn error occurred\n" && rm -f "/tmp/.*.fifo"' EXIT
 
@@ -51,6 +52,7 @@ container_manager="autodetect"
 container_name="my-distrobox"
 container_manager_additional_flags=""
 non_interactive=0
+distrobox_sudo_program="sudo"
 
 # Use cd + dirname + pwd so that we do not have relative paths in mount points
 # We're not using "realpath" here so that symlinks are not resolved this way
@@ -86,6 +88,7 @@ done
 [ -n "${DBX_CONTAINER_NAME}" ] && container_name="${DBX_CONTAINER_NAME}"
 [ -n "${DBX_SKIP_WORKDIR}" ] && skip_workdir="${DBX_SKIP_WORKDIR}"
 [ -n "${DBX_NON_INTERACTIVE}" ] && non_interactive="${DBX_NON_INTERACTIVE}"
+[ -n "${DBX_SUDO_PROGRAM}" ] && distrobox_sudo_program="${DBX_SUDO_PROGRAM}"
 
 # Print usage to stdout.
 # Arguments:
@@ -113,7 +116,10 @@ Options:
 	--additional-flags/-a:	additional flags to pass to the container manager command
 	--help/-h:		show this message
 	--root/-r:		launch podman/docker with root privileges. Note that if you need root this is the preferred
-				way over "sudo distrobox"
+				way over "sudo distrobox" (note: if using a program other than 'sudo' for root privileges is necessary,
+				refer to --sudo-program)
+	--sudo-program		when used with --root, specifies a program other than the default 'sudo' with which to launch podman/docker
+				with root privileges (common options include 'pkexec' for a graphical root authentication prompt, 'doas', and so on)
 	--dry-run/-d:		only print the container manager command generated
 	--verbose/-v:		show more verbosity
 	--version/-V:		show version
@@ -155,6 +161,13 @@ while :; do
 		-n | --name)
 			if [ -n "$2" ]; then
 				container_name="$2"
+				shift
+				shift
+			fi
+			;;
+		--sudo-program)
+			if [ -n "$2" ]; then
+				distrobox_sudo_program="$2"
 				shift
 				shift
 			fi
@@ -252,9 +265,18 @@ if [ "${verbose}" -ne 0 ]; then
 	container_manager="${container_manager} --log-level debug"
 fi
 
-# prepend sudo if we want podman or docker to be rootful
+# prepend sudo (or the specified sudo program) if we want podman or docker to be rootful
 if [ "${rootful}" -ne 0 ]; then
-	container_manager="sudo ${container_manager}"
+
+	# make sure the given sudo program exists
+	if ! command -v "${distrobox_sudo_program}" > /dev/null; then
+		printf >&2 "Invalid sudo program specified for usage in\n"
+		printf >&2 "managing rootful containers. Please specify\n"
+		printf >&2 "a valid command for the sudo program option, or\n"
+		printf >&2 "do not specify it to use the default 'sudo'."
+		exit 127
+	fi
+	container_manager="${distrobox_sudo_program} ${container_manager}"
 fi
 
 # Generate Podman or Docker command to execute.
diff --git a/distrobox-export b/distrobox-export
--- a/distrobox-export
+++ b/distrobox-export
@@ -40,7 +40,8 @@ extra_flags=""
 #	DBX_HOST_HOME is set in case container is created
 #	with custom --home directory
 host_home="${DISTROBOX_HOST_HOME:-"${HOME}"}"
-is_sudo=""
+is_sudo=0
+sudo_program=""
 rootful=""
 verbose=0
 version="1.3.2"
@@ -65,9 +66,9 @@ distrobox version: ${version}
 
 Usage:
 
-	distrobox-export --app mpv [--extra-flags "flags"] [--delete] [--sudo]
-	distrobox-export --service syncthing.service [--extra-flags "flags"] [--delete] [--sudo]
-	distrobox-export --bin /path/to/bin --export-path ~/.local/bin [--extra-flags "flags"] [--delete] [--sudo]
+	distrobox-export --app mpv [--extra-flags "flags"] [--delete] [--sudo] [--sudo-program]
+	distrobox-export --service syncthing.service [--extra-flags "flags"] [--delete] [--sudo] [--sudo-program]
+	distrobox-export --bin /path/to/bin --export-path ~/.local/bin [--extra-flags "flags"] [--delete] [--sudo] [--sudo-program]
 
 Options:
 
@@ -79,7 +80,10 @@ Options:
 				Defaults to (on \$container_name)
 	--export-path/-ep:	path where to export the binary
 	--extra-flags/-ef:	extra flags to add to the command
-	--sudo/-S:		specify if the exported item should be ran as sudo
+	--sudo/-S:		specify if the exported item should be ran as sudo (note: if using a program other than 'sudo' for root privileges on
+				the host is necessary, refer to --sudo-program)
+	--sudo-program		when used with --sudo, specifies a program other than the default 'sudo' with which to launch the exported app
+				with root privileges (common options include 'pkexec' for a graphical root authentication prompt, 'doas', and so on)
 	--help/-h:		show this message
 	--verbose/-v:		show more verbosity
 	--version/-V:		show version
@@ -126,9 +130,16 @@ while :; do
 				shift
 			fi
 			;;
-		-S | --sudo)
-			is_sudo="sudo"
+		-S | --sudo)  # keep param for backwards compatibility
+			is_sudo=1
 			shift
+			;;
+		--sudo-program)
+			if [ -n "$2" ]; then
+				sudo_program="$2"
+				shift
+				shift
+			fi
 			;;
 		-el | --export-label)
 			if [ -n "$2" ]; then
@@ -214,10 +225,23 @@ if [ -n "${exported_bin}" ] && [ -z "${dest_path}" ]; then
 	exit 2
 fi
 
+# If --sudo-program was specified, ensure --sudo was also given
+if [ "${is_sudo}" -eq 0 ] && [ -n "${sudo_program}" ]; then
+	printf >&2 "Error: The option --sudo-program may only be used together\n"
+	printf >&2 "with --sudo."
+	exit 2
+fi
+
+# If --sudo was specified, but --sudo-program wasn't, then default to using
+# "sudo" as the sudo program.
+if [ "${is_sudo}" -ne 0 ] && [ -z "${sudo_program}" ]; then
+	sudo_program="sudo"
+fi
+
 # We can assume this as we set it the same as container name during creation.
 container_name=$(uname -n | cut -d'.' -f1)
 # Prefix to add to an existing command to work throught the container
-container_command_prefix="${DISTROBOX_ENTER_PATH:-"distrobox-enter"} ${rootful} -n ${container_name} -- '${is_sudo} "
+container_command_prefix="${DISTROBOX_ENTER_PATH:-"distrobox-enter"} ${rootful} -n ${container_name} -- '${sudo_program} "
 if [ -z "${exported_app_label}" ]; then
 	exported_app_label=" (on ${container_name})"
 fi
@@ -234,7 +258,7 @@ generate_script() {
 # name: ${container_name}
 if [ ! -f /run/.containerenv ] && [ ! -f /.dockerenv ]; then
     ${DISTROBOX_ENTER_PATH:-"distrobox-enter"} ${rootful} -n ${container_name} -- \
-		${is_sudo} ${exported_bin} ${extra_flags} \$@
+		${sudo_program} ${exported_bin} ${extra_flags} \$@
 else
     ${exported_bin} \$@
 fi
diff --git a/distrobox-stop b/distrobox-stop
--- a/distrobox-stop
+++ b/distrobox-stop
@@ -23,6 +23,7 @@
 #	DBX_CONTAINER_MANAGER
 #   DBX_CONTAINER_NAME
 #   DBX_NON_INTERACTIVE
+#   DBX_SUDO_PROGRAM
 
 # Dont' run this command as sudo.
 if [ "$(id -u)" -eq 0 ]; then
@@ -38,6 +39,7 @@ container_name="my-distrobox"
 non_interactive=0
 rootful=0
 verbose=0
+distrobox_sudo_program="sudo"
 version="1.3.2"
 
 # Source configuration files, this is done in an hierarchy so local files have
@@ -60,6 +62,7 @@ done
 [ -n "${DBX_CONTAINER_MANAGER}" ] && container_manager="${DBX_CONTAINER_MANAGER}"
 [ -n "${DBX_CONTAINER_NAME}" ] && container_name="${DBX_CONTAINER_NAME}"
 [ -n "${DBX_NON_INTERACTIVE}" ] && non_interactive="${DBX_NON_INTERACTIVE}"
+[ -n "${DBX_SUDO_PROGRAM}" ] && distrobox_sudo_program="${DBX_SUDO_PROGRAM}"
 
 # Print usage to stdout.
 # Arguments:
@@ -81,7 +84,10 @@ Options:
 	--yes/-Y:		non-interactive, stop without asking
 	--help/-h:		show this message
 	--root/-r:		launch podman/docker with root privileges. Note that if you need root this is the preferred
-				way over "sudo distrobox"
+				way over "sudo distrobox" (note: if using a program other than 'sudo' for root privileges is necessary,
+				refer to --sudo-program)
+	--sudo-program		when used with --root, specifies a program other than the default 'sudo' with which to launch podman/docker
+				with root privileges (common options include 'pkexec' for a graphical root authentication prompt, 'doas', and so on)
 	--verbose/-v:		show more verbosity
 	--version/-V:		show version
 EOF
@@ -98,6 +104,13 @@ while :; do
 		-r | --root)
 			shift
 			rootful=1
+			;;
+		--sudo-program)
+			if [ -n "$2" ]; then
+				distrobox_sudo_program="$2"
+				shift
+				shift
+			fi
 			;;
 		-v | --verbose)
 			verbose=1
@@ -185,9 +198,18 @@ if [ "${verbose}" -ne 0 ]; then
 	container_manager="${container_manager} --log-level debug"
 fi
 
-# prepend sudo if we want podman or docker to be rootful
+# prepend sudo (or the specified sudo program) if we want podman or docker to be rootful
 if [ "${rootful}" -ne 0 ]; then
-	container_manager="sudo ${container_manager}"
+
+	# make sure the given sudo program exists
+	if ! command -v "${distrobox_sudo_program}" > /dev/null; then
+		printf >&2 "Invalid sudo program specified for usage in\n"
+		printf >&2 "managing rootful containers. Please specify\n"
+		printf >&2 "a valid command for the sudo program option, or\n"
+		printf >&2 "do not specify it to use the default 'sudo'."
+		exit 127
+	fi
+	container_manager="${distrobox_sudo_program} ${container_manager}"
 fi
 
 # Inspect the container we're working with.
