all: standardize when to do checks and set up logging

diff --git a/distrobox-enter b/distrobox-enter
--- a/distrobox-enter
+++ b/distrobox-enter
@@ -7,12 +7,6 @@
 
 trap '[ "$?" -ne 0 ] && printf "An error occurred\n"' EXIT
 
-# We depend on podman let's be sure we have it
-if ! command -v podman >/dev/null; then
-	printf >&2 "Missing dependency: podman\n"
-	exit 127
-fi
-
 # Defaults
 container_command="${SHELL:-"bash"} -l"
 container_name="fedora-toolbox-35"
@@ -85,6 +79,12 @@ set -o nounset
 # set verbosity
 if [ "${verbose}" -ne 0 ]; then
 	set -o xtrace
+fi
+
+# We depend on podman let's be sure we have it
+if ! command -v podman >/dev/null; then
+	printf >&2 "Missing dependency: podman\n"
+	exit 127
 fi
 
 # Generate Podman command to execute.
