Lint: use single tools instead of importing an action; reformat all to follow the style

diff --git a/distrobox b/distrobox
--- a/distrobox
+++ b/distrobox
@@ -42,7 +42,7 @@ version="1.2.15"
 # Outputs:
 #   print usage with examples.
 show_help() {
-	cat <<EOF
+	cat << EOF
 distrobox version: ${version}
 
 Choose one of the available commands:
@@ -66,36 +66,36 @@ shift
 # Simple wrapper to the distrobox utilities.
 # We just detect the 1st argument and launch the matching distrobox utility.
 case "${distrobox_command}" in
-create)
-	"${distrobox_path}"/distrobox-create "$@"
-	;;
-enter)
-	"${distrobox_path}"/distrobox-enter "$@"
-	;;
-list)
-	"${distrobox_path}"/distrobox-list "$@"
-	;;
-stop)
-	"${distrobox_path}"/distrobox-stop "$@"
-	;;
-rm)
-	"${distrobox_path}"/distrobox-rm "$@"
-	;;
--V | --version)
-	printf "distrobox: %s\n" "${version}"
-	exit 0
-	;;
-help | --help | -h)
-	if command -v man >/dev/null; then
-		man distrobox
+	create)
+		"${distrobox_path}"/distrobox-create "$@"
+		;;
+	enter)
+		"${distrobox_path}"/distrobox-enter "$@"
+		;;
+	list)
+		"${distrobox_path}"/distrobox-list "$@"
+		;;
+	stop)
+		"${distrobox_path}"/distrobox-stop "$@"
+		;;
+	rm)
+		"${distrobox_path}"/distrobox-rm "$@"
+		;;
+	-V | --version)
+		printf "distrobox: %s\n" "${version}"
 		exit 0
-	fi
-	show_help
-	exit 0
-	;;
-*) # Default case: If no more options then break out of the loop.
-	printf >&2 "Error: invalid command\n"
-	show_help
-	exit 1
-	;;
+		;;
+	help | --help | -h)
+		if command -v man > /dev/null; then
+			man distrobox
+			exit 0
+		fi
+		show_help
+		exit 0
+		;;
+	*) # Default case: If no more options then break out of the loop.
+		printf >&2 "Error: invalid command\n"
+		show_help
+		exit 1
+		;;
 esac
diff --git a/distrobox-create b/distrobox-create
--- a/distrobox-create
+++ b/distrobox-create
@@ -95,7 +95,7 @@ done
 # Outputs:
 #   print usage with examples.
 show_help() {
-	cat <<EOF
+	cat << EOF
 distrobox version: ${version}
 
 Usage:
@@ -140,94 +140,94 @@ EOF
 # Parse arguments
 while :; do
 	case $1 in
-	-h | --help)
-		# Call a "show_help" function to display a synopsis, then exit.
-		show_help
-		exit 0
-		;;
-	-v | --verbose)
-		verbose=1
-		shift
-		;;
-	-V | --version)
-		printf "distrobox: %s\n" "${version}"
-		exit 0
-		;;
-	-d | --dry-run)
-		shift
-		dryrun=1
-		;;
-	-I | --init)
-		shift
-		init=1
-		;;
-	-i | --image)
-		if [ -n "$2" ]; then
-			container_image="$2"
+		-h | --help)
+			# Call a "show_help" function to display a synopsis, then exit.
+			show_help
+			exit 0
+			;;
+		-v | --verbose)
+			verbose=1
 			shift
+			;;
+		-V | --version)
+			printf "distrobox: %s\n" "${version}"
+			exit 0
+			;;
+		-d | --dry-run)
 			shift
-		fi
-		;;
-	-n | --name)
-		if [ -n "$2" ]; then
-			container_name="$2"
+			dryrun=1
+			;;
+		-I | --init)
 			shift
+			init=1
+			;;
+		-i | --image)
+			if [ -n "$2" ]; then
+				container_image="$2"
+				shift
+				shift
+			fi
+			;;
+		-n | --name)
+			if [ -n "$2" ]; then
+				container_name="$2"
+				shift
+				shift
+			fi
+			;;
+		-c | --clone)
+			if [ -n "$2" ]; then
+				container_clone="$2"
+				shift
+				shift
+			fi
+			;;
+		-H | --home)
+			if [ -n "$2" ]; then
+				container_user_custom_home="$2"
+				shift
+				shift
+			fi
+			;;
+		-Y | --yes)
+			non_interactive=1
 			shift
-		fi
-		;;
-	-c | --clone)
-		if [ -n "$2" ]; then
-			container_clone="$2"
+			;;
+		--volume)
+			if [ -n "$2" ]; then
+				container_manager_additional_flags="${container_manager_additional_flags} ${1} ${2}"
+				shift
+				shift
+			fi
+			;;
+		-a | --additional-flags)
+			if [ -n "$2" ]; then
+				container_manager_additional_flags="${container_manager_additional_flags} ${2}"
+				shift
+				shift
+			fi
+			;;
+		--init-hooks)
+			if [ -n "$2" ]; then
+				container_init_hook="$2"
+				shift
+				shift
+			fi
+			;;
+		--) # End of all options.
 			shift
-			shift
-		fi
-		;;
-	-H | --home)
-		if [ -n "$2" ]; then
-			container_user_custom_home="$2"
-			shift
-			shift
-		fi
-		;;
-	-Y | --yes)
-		non_interactive=1
-		shift
-		;;
-	--volume)
-		if [ -n "$2" ]; then
-			container_manager_additional_flags="${container_manager_additional_flags} ${1} ${2}"
-			shift
-			shift
-		fi
-		;;
-	-a | --additional-flags)
-		if [ -n "$2" ]; then
-			container_manager_additional_flags="${container_manager_additional_flags} ${2}"
-			shift
-			shift
-		fi
-		;;
-	--init-hooks)
-		if [ -n "$2" ]; then
-			container_init_hook="$2"
-			shift
-			shift
-		fi
-		;;
-	--) # End of all options.
-		shift
-		break
-		;;
-	*) # Default case: If no more options then break out of the loop.
-		# If we have a flagless option and container_name is not specified
-		# then let's accept argument as container_name
-		if [ -n "$1" ]; then
-			container_name="$1"
-			shift
-		else
 			break
-		fi
-		;;
+			;;
+		*) # Default case: If no more options then break out of the loop.
+			# If we have a flagless option and container_name is not specified
+			# then let's accept argument as container_name
+			if [ -n "$1" ]; then
+				container_name="$1"
+				shift
+			else
+				break
+			fi
+			;;
 	esac
 done
 
@@ -265,30 +265,30 @@ fi
 # We depend on a container manager let's be sure we have it
 # First we use podman, else docker
 case "${container_manager}" in
-autodetect)
-	if command -v podman >/dev/null; then
+	autodetect)
+		if command -v podman > /dev/null; then
+			container_manager="podman"
+		elif command -v docker > /dev/null; then
+			container_manager="docker"
+		else
+			container_manager="not_found"
+		fi
+		;;
+	podman)
 		container_manager="podman"
-	elif command -v docker >/dev/null; then
+		;;
+	docker)
 		container_manager="docker"
-	else
+		;;
+	*)
+		printf >&2 "Invalid input %s.\n" "${container_manager}"
+		printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
 		container_manager="not_found"
-	fi
-	;;
-podman)
-	container_manager="podman"
-	;;
-docker)
-	container_manager="docker"
-	;;
-*)
-	printf >&2 "Invalid input %s.\n" "${container_manager}"
-	printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
-	container_manager="not_found"
-	;;
+		;;
 esac
 
 # Be sure we have a container manager to work with.
-if ! command -v "${container_manager}" >/dev/null; then
+if ! command -v "${container_manager}" > /dev/null; then
 	# Error: we need at least one between docker or podman.
 	printf >&2 "Missing dependency: we need a container manager.\n"
 	printf >&2 "Please install one of podman or docker.\n"
@@ -335,7 +335,7 @@ clone_container() {
 	# Commit current container state to a new image tag
 	printf >&2 "Duplicating %s...\n" "${container_clone}"
 	if ! ${container_manager} container commit \
-		"${container_source_id}" "${container_commit_tag}" >/dev/null; then
+		"${container_source_id}" "${container_commit_tag}" > /dev/null; then
 
 		printf >&2 "Cannot clone container: %s\n" "${container_clone}"
 		return 1
@@ -405,7 +405,6 @@ generate_command() {
 	# to /run/shm, instead of the other way around.
 	# Resolve this detecting if /dev/shm is a symlink and mount original
 	# source also in the container.
-	# shellcheck disable=SC2312
 	if [ -L "/dev/shm" ]; then
 		result_command="${result_command}
 			--volume $(realpath /dev/shm):$(realpath /dev/shm)"
@@ -514,7 +513,7 @@ fi
 
 # Check if the container already exists.
 # If it does, notify the user and exit.
-if ${container_manager} inspect --type container "${container_name}" >/dev/null 2>&1; then
+if ${container_manager} inspect --type container "${container_name}" > /dev/null 2>&1; then
 	printf "Distrobox named '%s' already exists.\n" "${container_name}"
 	printf "To enter, run:\n"
 	printf "\tdistrobox-enter --name %s\n" "${container_name}"
@@ -528,7 +527,7 @@ if [ -n "${container_clone}" ]; then
 fi
 # First, check if the image exists in the host.
 # If not prompt to download it.
-if ! ${container_manager} inspect --type image "${container_image}" >/dev/null 2>&1; then
+if ! ${container_manager} inspect --type image "${container_image}" > /dev/null 2>&1; then
 	if [ "${non_interactive}" -eq 0 ]; then
 		# Prompt to download it.
 		printf >&2 "Image %s not found.\n" "${container_image}"
@@ -541,20 +540,20 @@ if ! ${container_manager} inspect --type image "${container_image}" >/dev/null 2
 
 	# Accept only y,Y,Yes,yes,n,N,No,no.
 	case "${response}" in
-	y | Y | Yes | yes | YES)
-		# Pull the image
-		${container_manager} pull "${container_image}"
-		;;
-	n | N | No | no | NO)
-		printf >&2 "next time, run this command first:\n"
-		printf >&2 "\t%s pull %s\n" "${container_manager}" "${container_image}"
-		exit 0
-		;;
-	*) # Default case: If no more options then break out of the loop.
-		printf >&2 "Invalid input.\n"
-		printf >&2 "The available choices are: y,Y,Yes,yes,YES or n,N,No,no,NO.\nExiting.\n"
-		exit 1
-		;;
+		y | Y | Yes | yes | YES)
+			# Pull the image
+			${container_manager} pull "${container_image}"
+			;;
+		n | N | No | no | NO)
+			printf >&2 "next time, run this command first:\n"
+			printf >&2 "\t%s pull %s\n" "${container_manager}" "${container_image}"
+			exit 0
+			;;
+		*) # Default case: If no more options then break out of the loop.
+			printf >&2 "Invalid input.\n"
+			printf >&2 "The available choices are: y,Y,Yes,yes,YES or n,N,No,no,NO.\nExiting.\n"
+			exit 1
+			;;
 	esac
 fi
 
diff --git a/distrobox-enter b/distrobox-enter
--- a/distrobox-enter
+++ b/distrobox-enter
@@ -81,7 +81,7 @@ done
 # Outputs:
 #   print usage with examples.
 show_help() {
-	cat <<EOF
+	cat << EOF
 distrobox version: ${version}
 
 Usage:
@@ -108,56 +108,56 @@ EOF
 # Parse arguments
 while :; do
 	case $1 in
-	-h | --help)
-		# Call a "show_help" function to display a synopsis, then exit.
-		show_help
-		exit 0
-		;;
-	-v | --verbose)
-		shift
-		verbose=1
-		;;
-	-T | -H | --no-tty)
-		shift
-		headless=1
-		;;
-	-V | --version)
-		printf "distrobox: %s\n" "${version}"
-		exit 0
-		;;
-	-d | --dry-run)
-		shift
-		dryrun=1
-		;;
-	-n | --name)
-		if [ -n "$2" ]; then
-			container_name="$2"
+		-h | --help)
+			# Call a "show_help" function to display a synopsis, then exit.
+			show_help
+			exit 0
+			;;
+		-v | --verbose)
 			shift
+			verbose=1
+			;;
+		-T | -H | --no-tty)
 			shift
-		fi
-		;;
-	-a | --additional-flags)
-		if [ -n "$2" ]; then
-			container_manager_additional_flags="${container_manager_additional_flags} ${2}"
+			headless=1
+			;;
+		-V | --version)
+			printf "distrobox: %s\n" "${version}"
+			exit 0
+			;;
+		-d | --dry-run)
 			shift
+			dryrun=1
+			;;
+		-n | --name)
+			if [ -n "$2" ]; then
+				container_name="$2"
+				shift
+				shift
+			fi
+			;;
+		-a | --additional-flags)
+			if [ -n "$2" ]; then
+				container_manager_additional_flags="${container_manager_additional_flags} ${2}"
+				shift
+				shift
+			fi
+			;;
+		-e | --exec | --)
 			shift
-		fi
-		;;
-	-e | --exec | --)
-		shift
-		container_command=$*
-		break
-		;;
-	*) # Default case: If no more options then break out of the loop.
-		# If we have a flagless option and container_name is not specified
-		# then let's accept argument as container_name
-		if [ -n "$1" ]; then
-			container_name="$1"
-			shift
-		else
+			container_command=$*
 			break
-		fi
-		;;
+			;;
+		*) # Default case: If no more options then break out of the loop.
+			# If we have a flagless option and container_name is not specified
+			# then let's accept argument as container_name
+			if [ -n "$1" ]; then
+				container_name="$1"
+				shift
+			else
+				break
+			fi
+			;;
 	esac
 done
 
@@ -171,30 +171,30 @@ fi
 # We depend on a container manager let's be sure we have it
 # First we use podman, else docker
 case "${container_manager}" in
-autodetect)
-	if command -v podman >/dev/null; then
+	autodetect)
+		if command -v podman > /dev/null; then
+			container_manager="podman"
+		elif command -v docker > /dev/null; then
+			container_manager="docker"
+		else
+			container_manager="not_found"
+		fi
+		;;
+	podman)
 		container_manager="podman"
-	elif command -v docker >/dev/null; then
+		;;
+	docker)
 		container_manager="docker"
-	else
+		;;
+	*)
+		printf >&2 "Invalid input %s.\n" "${container_manager}"
+		printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
 		container_manager="not_found"
-	fi
-	;;
-podman)
-	container_manager="podman"
-	;;
-docker)
-	container_manager="docker"
-	;;
-*)
-	printf >&2 "Invalid input %s.\n" "${container_manager}"
-	printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
-	container_manager="not_found"
-	;;
+		;;
 esac
 
 # Be sure we have a container manager to work with.
-if ! command -v "${container_manager}" >/dev/null; then
+if ! command -v "${container_manager}" > /dev/null; then
 	# Error: we need at least one between docker or podman.
 	printf >&2 "Missing dependency: we need a container manager.\n"
 	printf >&2 "Please install one of podman or docker.\n"
@@ -213,10 +213,9 @@ fi
 #
 # This is not necessary on docker as it is already handled
 # in this way.
-# shellcheck disable=SC2312
 if [ -z "${container_manager#*podman*}" ] &&
 	[ -S "/run/user/$(id -ru)/podman/podman.sock" ] &&
-	systemctl --user status podman.socket >/dev/null; then
+	systemctl --user status podman.socket > /dev/null; then
 
 	container_manager="${container_manager} --remote"
 fi
@@ -364,7 +363,7 @@ if [ "${container_status}" != "running" ]; then
 	# Here, we save the timestamp before launching the start command, so we can
 	# be sure we're working with this very same session of logs later.
 	log_timestamp="$(date +%FT%T.%N%:z)"
-	${container_manager} start "${container_name}" >/dev/null
+	${container_manager} start "${container_name}" > /dev/null
 
 	printf >&2 "Starting container %s\n" "${container_name}"
 	printf >&2 "run this command to follow along:\n"
@@ -378,26 +377,26 @@ if [ "${container_status}" != "running" ]; then
 	while :; do
 		container_manager_log="$(${container_manager} logs -t \
 			--since "${log_timestamp}" \
-			"${container_name}" 2>/dev/null)"
+			"${container_name}" 2> /dev/null)"
 		case "${container_manager_log}" in
-		*"Error"*)
-			printf >&2 "%s\n" "${container_manager_log}"
-			exit 1
-			;;
-		*"container_setup_done"*)
-			break
-			;;
-		*)
-			printf >&2 "."
-			sleep 1
-			;;
+			*"Error"*)
+				printf >&2 "%s\n" "${container_manager_log}"
+				exit 1
+				;;
+			*"container_setup_done"*)
+				break
+				;;
+			*)
+				printf >&2 "."
+				sleep 1
+				;;
 		esac
 	done
 	printf >&2 "\ndone!\n"
 	# Print eventual warnings in the log.
 	${container_manager} logs -t \
 		--since "${log_timestamp}" \
-		"${container_name}" 2>/dev/null | grep "Warning" >&2 || :
+		"${container_name}" 2> /dev/null | grep "Warning" >&2 || :
 fi
 
 # Generate the exec command and run it
diff --git a/distrobox-export b/distrobox-export
--- a/distrobox-export
+++ b/distrobox-export
@@ -46,7 +46,7 @@ version="1.2.15"
 # We depend on some commands, let's be sure we have them
 base_dependencies="basename grep sed find"
 for dep in ${base_dependencies}; do
-	if ! command -v "${dep}" >/dev/null; then
+	if ! command -v "${dep}" > /dev/null; then
 		printf >&2 "Missing dependency: %s\n" "${dep}"
 		exit 127
 	fi
@@ -58,7 +58,7 @@ done
 # Outputs:
 #   print usage with examples.
 show_help() {
-	cat <<EOF
+	cat << EOF
 distrobox version: ${version}
 
 Usage:
@@ -88,74 +88,74 @@ EOF
 # Parse arguments
 while :; do
 	case $1 in
-	-h | --help)
-		# Call a "show_help" function to display a synopsis, then exit.
-		show_help
-		exit 0
-		;;
-	-v | --verbose)
-		shift
-		verbose=1
-		;;
-	-V | --version)
-		printf "distrobox: %s\n" "${version}"
-		exit 0
-		;;
-	-a | --app)
-		if [ -n "$2" ]; then
-			export_action="app"
-			exported_app="$2"
+		-h | --help)
+			# Call a "show_help" function to display a synopsis, then exit.
+			show_help
+			exit 0
+			;;
+		-v | --verbose)
 			shift
+			verbose=1
+			;;
+		-V | --version)
+			printf "distrobox: %s\n" "${version}"
+			exit 0
+			;;
+		-a | --app)
+			if [ -n "$2" ]; then
+				export_action="app"
+				exported_app="$2"
+				shift
+				shift
+			fi
+			;;
+		-b | --bin)
+			if [ -n "$2" ]; then
+				export_action="bin"
+				exported_bin="$2"
+				shift
+				shift
+			fi
+			;;
+		-s | --service)
+			if [ -n "$2" ]; then
+				export_action="service"
+				exported_service="$2"
+				shift
+				shift
+			fi
+			;;
+		-S | --sudo)
+			is_sudo="sudo"
 			shift
-		fi
-		;;
-	-b | --bin)
-		if [ -n "$2" ]; then
-			export_action="bin"
-			exported_bin="$2"
+			;;
+		-el | --export-label)
+			if [ -n "$2" ]; then
+				exported_app_label="$2"
+				shift
+				shift
+			fi
+			;;
+		-ep | --export-path)
+			if [ -n "$2" ]; then
+				dest_path="$2"
+				shift
+				shift
+			fi
+			;;
+		-ef | --extra-flags)
+			if [ -n "$2" ]; then
+				extra_flags="$2"
+				shift
+				shift
+			fi
+			;;
+		-d | --delete)
+			exported_delete=1
 			shift
-			shift
-		fi
-		;;
-	-s | --service)
-		if [ -n "$2" ]; then
-			export_action="service"
-			exported_service="$2"
-			shift
-			shift
-		fi
-		;;
-	-S | --sudo)
-		is_sudo="sudo"
-		shift
-		;;
-	-el | --export-label)
-		if [ -n "$2" ]; then
-			exported_app_label="$2"
-			shift
-			shift
-		fi
-		;;
-	-ep | --export-path)
-		if [ -n "$2" ]; then
-			dest_path="$2"
-			shift
-			shift
-		fi
-		;;
-	-ef | --extra-flags)
-		if [ -n "$2" ]; then
-			extra_flags="$2"
-			shift
-			shift
-		fi
-		;;
-	-d | --delete)
-		exported_delete=1
-		shift
-		;;
-	*) # Default case: If no more options then break out of the loop.
-		break ;;
+			;;
+		*) # Default case: If no more options then break out of the loop.
+			break ;;
 	esac
 done
 
@@ -217,7 +217,7 @@ fi
 # Outputs:
 #   print generated script.
 generate_script() {
-	cat <<EOF
+	cat << EOF
 #!/bin/sh
 # distrobox_binary
 # name: ${container_name}
@@ -276,7 +276,7 @@ export_binary() {
 	fi
 
 	# create the script from template and write to file
-	if generate_script >"${dest_file}"; then
+	if generate_script > "${dest_file}"; then
 		chmod +x "${dest_file}"
 		printf "%s from %s exported successfully in %s.\nOK!\n" \
 			"${exported_bin}" "${container_name}" "${dest_path}"
@@ -301,14 +301,14 @@ export_binary() {
 #	or error code.
 export_application() {
 	# Ensure the app we're exporting is installed
-	if ! command -v "${exported_app}" >/dev/null; then
+	if ! command -v "${exported_app}" > /dev/null; then
 		printf >&2 "Error: trying to export a non-installed application.\n"
 		return 127
 	fi
 
 	# Find desktop file for the application to export
 	desktop_files=$(grep -ril "${exported_app}" /usr/share/applications/* /var/lib/flatpak/exports/share/applications/* || :)
-	icon_files=$(find /usr/share/icons /usr/share/pixmaps /var/lib/flatpak/exports/share/icons -iname "*${exported_app}*" 2>/dev/null || :)
+	icon_files=$(find /usr/share/icons /usr/share/pixmaps /var/lib/flatpak/exports/share/icons -iname "*${exported_app}*" 2> /dev/null || :)
 	# Check that we found some desktop files first.
 	if [ -z "${desktop_files}" ]; then
 		printf >&2 "Error: cannot find any desktop files.\n"
@@ -363,9 +363,9 @@ export_application() {
 				sed 's|^Exec=.*|&"|g' |
 				sed "s|^TryExec=.*|TryExec=true|g" |
 				sed "s|Name.*|& ${exported_app_label}|g" \
-					>"/run/host/${host_home}/.local/share/applications/${desktop_home_file}"
+					> "/run/host/${host_home}/.local/share/applications/${desktop_home_file}"
 			if ! grep -q "StartupWMClass" "/run/host/${host_home}/.local/share/applications/${desktop_home_file}"; then
-				printf "StartupWMClass=%s\n" "${exported_app}" >>"/run/host/${host_home}/.local/share/applications/${desktop_home_file}"
+				printf "StartupWMClass=%s\n" "${exported_app}" >> "/run/host/${host_home}/.local/share/applications/${desktop_home_file}"
 			fi
 			# in the end we add the final quote we've opened in the "container_command_prefix"
 		fi
@@ -396,7 +396,7 @@ export_service() {
 	service_file=$(find \
 		/etc/systemd/system/ /lib/systemd/system/ /usr/lib/systemd/system/ \
 		"${host_home}"/.config/systemd/user/ \
-		-type f -name "${exported_service}*" 2>/dev/null | tail -1)
+		-type f -name "${exported_service}*" 2> /dev/null | tail -1)
 	# Check that we found some service files first.
 	if [ -z "${service_file}" ]; then
 		printf >&2 "Error: cannot find any service file for %s.\n" "${exported_service}"
@@ -435,10 +435,10 @@ export_service() {
 	if [ ! -d "/run/host/${host_home}/.config/systemd/user/" ]; then
 		mkdir -p "/run/host/${host_home}/.config/systemd/user/"
 	fi
-	cat "${service_file}" >"${exported_service_fullpath}" 2>/dev/null
+	cat "${service_file}" > "${exported_service_fullpath}" 2> /dev/null
 	for exec_cmd in ExecStart ExecStartPre ExecStartPost ExecReload ExecStop ExecStopPost; do
 		# Save to temp file
-		cat "${exported_service_fullpath}" >"${temp_file}" 2>/dev/null
+		cat "${exported_service_fullpath}" > "${temp_file}" 2> /dev/null
 		# Add prefix only if not present
 		if ! grep "${exec_cmd}" "${temp_file}" | grep -q "${container_command_prefix}"; then
 			# Add commmand_prefix
@@ -446,7 +446,7 @@ export_service() {
 			# Add closing quote
 			sed "s|^${exec_cmd}=|${exec_cmd}=${container_command_prefix}|g" "${temp_file}" |
 				sed "s|^${exec_cmd}=.*|& ${extra_flags}|g" |
-				sed "s|^${exec_cmd}=.*|&\"|g" >"${exported_service_fullpath}"
+				sed "s|^${exec_cmd}=.*|&\"|g" > "${exported_service_fullpath}"
 			# in the end we add the final quote we've opened in the "container_command_prefix"
 		fi
 	done
@@ -464,18 +464,18 @@ export_service() {
 
 # Main routine
 case "${export_action}" in
-app)
-	export_application
-	;;
-bin)
-	export_binary
-	;;
-service)
-	export_service
-	;;
-*)
-	printf >&2 "Invalid arguments, choose an action below.\n"
-	show_help
-	exit 2
-	;;
+	app)
+		export_application
+		;;
+	bin)
+		export_binary
+		;;
+	service)
+		export_service
+		;;
+	*)
+		printf >&2 "Invalid arguments, choose an action below.\n"
+		show_help
+		exit 2
+		;;
 esac
diff --git a/distrobox-list b/distrobox-list
--- a/distrobox-list
+++ b/distrobox-list
@@ -58,7 +58,7 @@ done
 # Outputs:
 #   print usage with examples.
 show_help() {
-	cat <<EOF
+	cat << EOF
 distrobox version: ${version}
 
 Usage:
@@ -76,25 +76,25 @@ EOF
 # Parse arguments
 while :; do
 	case $1 in
-	-h | --help)
-		# Call a "show_help" function to display a synopsis, then exit.
-		show_help
-		exit 0
-		;;
-	-v | --verbose)
-		verbose=1
-		shift
-		;;
-	-V | --version)
-		printf "distrobox: %s\n" "${version}"
-		exit 0
-		;;
-	--) # End of all options.
-		shift
-		break
-		;;
-	*) # Default case: If no more options then break out of the loop.
-		break ;;
+		-h | --help)
+			# Call a "show_help" function to display a synopsis, then exit.
+			show_help
+			exit 0
+			;;
+		-v | --verbose)
+			verbose=1
+			shift
+			;;
+		-V | --version)
+			printf "distrobox: %s\n" "${version}"
+			exit 0
+			;;
+		--) # End of all options.
+			shift
+			break
+			;;
+		*) # Default case: If no more options then break out of the loop.
+			break ;;
 	esac
 done
 
@@ -108,30 +108,30 @@ fi
 # We depend on a container manager let's be sure we have it
 # First we use podman, else docker
 case "${container_manager}" in
-autodetect)
-	if command -v podman >/dev/null; then
+	autodetect)
+		if command -v podman > /dev/null; then
+			container_manager="podman"
+		elif command -v docker > /dev/null; then
+			container_manager="docker"
+		else
+			container_manager="not_found"
+		fi
+		;;
+	podman)
 		container_manager="podman"
-	elif command -v docker >/dev/null; then
+		;;
+	docker)
 		container_manager="docker"
-	else
+		;;
+	*)
+		printf >&2 "Invalid input %s.\n" "${container_manager}"
+		printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
 		container_manager="not_found"
-	fi
-	;;
-podman)
-	container_manager="podman"
-	;;
-docker)
-	container_manager="docker"
-	;;
-*)
-	printf >&2 "Invalid input %s.\n" "${container_manager}"
-	printf >&2 "The available choices are: 'autodetect', 'podman', 'docker'\n"
-	container_manager="not_found"
-	;;
+		;;
 esac
 
 # Be sure we have a container manager to work with.
-if ! command -v "${container_manager}" >/dev/null; then
+if ! command -v "${container_manager}" > /dev/null; then
 	# Error: we need at least one between docker or podman.
 	printf >&2 "Missing dependency: we need a container manager.\n"
 	printf >&2 "Please install one of podman or docker.\n"
