add write permissions check
Signed-off-by: Mišo Barišić <me@misobarisic.com>

diff --git a/install b/install
--- a/install
+++ b/install
@@ -145,5 +145,8 @@ else
 	fi
 fi
 
+[ ! -w "${dest_path}" ] && printf >&2 "Cannot write into %s, permission denied.\n" "${dest_path}" && exit 1
+[ ! -w "${man_dest_path}" ] && printf >&2 "Cannot write into %s, permission denied.\n" "${man_dest_path}" && exit 1
+
 printf >&2 "Successfully installed to %s.\n" "${dest_path}"
 printf >&2 "Be sure that %s is in your \$PATH environment variable for it to work.\n" "${dest_path}"
diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -85,6 +85,9 @@ if [ "${verbose}" -ne 0 ]; then
 	set -o xtrace
 fi
 
+[ ! -w "${dest_path}" ] && printf >&2 "Cannot write into %s, permission denied.\n" "${dest_path}" && exit 1
+[ ! -w "${man_dest_path}" ] && printf >&2 "Cannot write into %s, permission denied.\n" "${man_dest_path}" && exit 1
+
 # uninstall
 for file in "${dest_path}/distrobox"*; do
 	[ -e "${file}" ] && rm "${file}"
