Improve dependency checking, fix #1 Use $SHELL as shell also in containers, fix #2 Fix sudoers file on some distributions Fix missing icons for graphical apps inside toolbox

diff --git a/toolbox_create b/toolbox_create
--- a/toolbox_create
+++ b/toolbox_create
@@ -3,16 +3,21 @@
 
 trap '[ "$?" -ne 0 ] && echo An error occurred' EXIT
 
-container_user_home="${HOME}"
-container_user_name="${USER}"
-container_user_gid="$(id -rg)"
-container_user_uid="$(id -ru)"
-toolbox_entrypoint_path="$(command -v toolbox_init)"
-toolbox_export_path="$(command -v toolbox_export)"
+# We depend on podman let's be sure we have it
+if ! command -v podman >/dev/null; then
+	echo "Missing dependency: podman"
+	exit 127
+fi
 
 # Defaults
 container_image="registry.fedoraproject.org/fedora-toolbox:35"
 container_name="fedora-toolbox-35"
+container_user_gid="$(id -rg)"
+container_user_home="${HOME}"
+container_user_name="${USER}"
+container_user_uid="$(id -ru)"
+toolbox_entrypoint_path="$(command -v toolbox_init)"
+toolbox_export_path="$(command -v toolbox_export)"
 verbose=0
 
 # Print usage to stdout.
@@ -96,6 +101,7 @@ generate_command() {
 	#
 	# also mount the toolbox_init utility as the container entrypoint
 	echo "--name ${container_name}
+	--env=SHELL=${SHELL}
 	--network host
 	--no-hosts
 	--pid host
@@ -104,9 +110,12 @@ generate_command() {
 	--ulimit host
 	--user root:root
 	--userns keep-id
-	--volume ${toolbox_entrypoint_path}:/usr/bin/entrypoint:ro
-	--volume ${toolbox_export}:/usr/bin/toolbox_export:ro
-	--volume ${container_user_home}:${container_user_home}:rslave
+	--volume ${toolbox_entrypoint_path}:/usr/bin/entrypoint:ro"
+	# let's check if we can include toolbox_export or not
+	if [ -n "${toolbox_export_path}" ]; then
+		echo "--volume ${toolbox_export_path}:/usr/bin/toolbox_export:ro"
+	fi
+	echo "--volume ${container_user_home}:${container_user_home}:rslave
 	--volume /:/run/host:rslave
 	--volume /dev:/dev:rslave
 	--volume /etc:/run/host/etc
@@ -131,7 +140,10 @@ generate_command() {
 		echo "--volume ${socket}:${socket}"
 	done
 	# now execute the entrypoint, refer to `toolbox_init -h` for instructions
-	echo "${container_image} /usr/bin/entrypoint -v --name ${container_user_name} --user ${container_user_uid} --group ${container_user_gid} --home ${container_user_home}"
+	echo "${container_image}
+	/usr/bin/entrypoint -v --name ${container_user_name}
+	--user ${container_user_uid} --group ${container_user_gid}
+	--home ${container_user_home}"
 }
 
 # First, check if the image exists in the host
diff --git a/toolbox_enter b/toolbox_enter
--- a/toolbox_enter
+++ b/toolbox_enter
@@ -3,10 +3,16 @@
 
 trap '[ "$?" -ne 0 ] && echo An error occurred' EXIT
 
+# We depend on podman let's be sure we have it
+if ! command -v podman >/dev/null; then
+	echo "Missing dependency: podman"
+	exit 127
+fi
+
 # Defaults
 verbose=0
 container_name="fedora-toolbox-35"
-container_command="bash -l"
+container_command="${SHELL} -l"
 
 # Print usage to stdout.
 # Arguments:
diff --git a/toolbox_export b/toolbox_export
--- a/toolbox_export
+++ b/toolbox_export
@@ -8,6 +8,15 @@ container_app=""
 container_app_delete=0
 verbose=0
 
+# We depend on some commands, let's be sure we have them
+base_dependencies="basename grep sed find"
+for dep in ${base_dependencies}; do
+	if ! command -v "${dep}" >/dev/null; then
+		echo "Missing dependency: ${dep}"
+		exit 127
+	fi
+done
+
 # Print usage to stdout.
 # Arguments:
 #   None
@@ -23,6 +32,7 @@ show_help() {
 	Arguments:
 		--app/-a:		name of the application to export
 		--service/-s:		name of the service to export
+		--delete/-d:		delete exported application or service
 		--help/-h:		show this message
 		-v:			show more verbosity
 	"
@@ -92,6 +102,11 @@ container_command_prefix="${TOOLBOX_HOST_PATH} --name ${container_name} -e "
 
 # Work on a desktop app export
 if [ -n "${container_app}" ]; then
+	# Ensure the app we're exporting is installed
+	if ! command -v "${container_app}" >/dev/null; then
+		echo "Error: trying to export a non-installed application"
+		exit 127
+	fi
 	# Find desktop file for the application to export
 	desktop_files=$(grep -ril "${container_app}" /usr/share/applications)
 	icon_files=$(find /usr/share/icons -iname "*${container_app}*")
@@ -127,6 +142,11 @@ if [ -n "${container_app}" ]; then
 		fi
 	done
 elif [ -n "${container_service}" ]; then
+	# If we're managing services, let's be sure we have systemctl
+	if ! command -v systemctl >/dev/null; then
+		echo "Missing dependency: systemd"
+		exit 127
+	fi
 	# Ensure we're working with fresh data
 	systemctl --user daemon-reload
 	# Fetch original service file
@@ -142,7 +162,8 @@ elif [ -n "${container_service}" ]; then
 		systemctl --user cat "${container_service}.service" >"${temp_file}" 2>/dev/null
 		# Add prefix only if not present
 		if ! grep "${cmd}" "${temp_file}" | grep -q "${container_command_prefix}"; then
-			tail -n+2 "${temp_file}" | sed "s|^${cmd}=|${cmd}=${container_command_prefix} |g" >"${service_file}"
+			tail -n+2 "${temp_file}" |
+				sed "s|^${cmd}=|${cmd}=${container_command_prefix} |g" >"${service_file}"
 		fi
 	done
 	# Cleanup
