toolbox_init: add installation of sudo and user tools to support non-toolbox images

diff --git a/toolbox_init b/toolbox_init
--- a/toolbox_init
+++ b/toolbox_init
@@ -168,6 +168,33 @@ for mount in $HOST_MOUNTS; do
 	mount_bind /run/host"${mount}" "${mount}" rw
 done
 
+# Check if sudo is installed
+if ! command -v sudo || ! command -v passwd || ! command -v useradd || ! command -v usermod; then
+	if command -v apk; then
+		apk add --no-cache sudo shadow
+	elif command -v apt; then
+		apt update && apt install -y --no-install-recommends sudo shadow
+	elif command -v dnf; then
+		dnf install -y --setopt=install_weak_deps=False sudo shadow-utils passwd
+	elif command -v pacman; then
+		pacman -Sy --noconfirm sudo shadow
+	elif command -v yum; then
+		yum install -y --setopt=install_weak_deps=False sudo shadow-utils passwd
+	elif command -v zypper; then
+		zypper install -y --no-recommends sudo shadow
+	else
+		echo "FAILED TO INSTALL BASE DEPENDENCIES"
+		exit 127
+	fi
+fi
+
+# Ensure passwordless sudo is set up for user
+if ! mkdir -p /etc/sudoers.d/; then
+	exit 1
+fi
+echo "${container_user_name} ALL = (root) NOPASSWD:ALL" >"/etc/sudoers.d/${container_user_name}"
+echo "Defaults !fqdn" >>"/etc/sudoers.d/${container_user_name}"
+
 # Let's add our user to the container
 # if the user already exists, just add it to the sudoers groups
 if ! useradd \
@@ -179,11 +206,12 @@ if ! useradd \
 	--groups "$(list_sudo_groups)" \
 	"${container_user_name}"; then
 
-	usermod -aG wheel "${container_user_name}"
+	usermod -aG "$(list_sudo_groups)" "${container_user_name}"
 fi
 # Delete password for root and user
 passwd --delete "${container_user_name}"
 passwd --delete root
 
+echo "container_setup_done"
 # Keepalive loop
 sleep infinity
