install/uninstall: do not break compatibility with old installers

diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -19,7 +19,7 @@
 
 # POSIX
 
-dest_path="/usr/local"
+dest_path="/usr/local/bin"
 verbose=0
 
 # Print usage to stdout.
@@ -29,7 +29,7 @@ verbose=0
 #   print usage with examples.
 show_help() {
 	cat <<EOF
-uninstall -p /usr/local
+uninstall -p /usr/local/bin
 
 Options:
 	--path/-p:		path where to deploy the files (default /usr/local)
@@ -71,15 +71,14 @@ fi
 
 # Ensure the foundamental variables are set and not empty, we will not proceed if
 # they are not all set.
-[ ! -w "${dest_path}/bin" ] && printf >&2 "Cannot write into %s, permission denied.\n" "${dest_path}/bin" && exit 1
-[ ! -w "${dest_path}/share/man/man1" ] && printf >&2 "Cannot write into %s, permission denied.\n" "${dest_path}/share/man/man1" && exit 1
+[ ! -w "${dest_path}" ] && printf >&2 "Cannot write into %s, permission denied.\n" "${dest_path}/bin" && exit 1
 
 # uninstall
 if [ -f "${dest_path}/distrobox-enter" ]; then
 	for file in distrobox*; do
 		rm -i "${dest_path}/${file}"
 	done
-	for file in "${dest_path}/share/man/man1/distrobox"*; do
+	for file in "${dest_path}/../share/man/man1/distrobox"*; do
 		rm -i "${file}"
 	done
 	echo "Thank you for using Distrobox. Uninstall complete."
